### ISSUE TITLE
Is Firebird 1.5 no longer supported?

### ISSUE THREAD

**Issue by fishcodelib** [FirebirdSQL/NETProvider#1004]
https://github.com/FirebirdSQL/NETProvider/commit/ec9c4247ac5fbd07787270e5a7d883771d39f7ca
This change breaks the compatibility with the older version 1.5 of Firebird because it doesn't support to use alias in ORDER BY.

**Comment by cincuranet** [comment]
Yes. FB 1.5 is no longer actively supported. Same with 2.0, 2.1 at the moment.
