### ISSUE TITLE
Add logging of transaction operations, i.e. begin transaction, commit ...

### ISSUE THREAD

**Issue by krilbe** [FirebirdSQL/NETProvider#1007]
Logging of executed SQL is available, which is good, but it would be nice to also have transaction operations in the log. It would be a great addition when analyzing what's happening. SQL logging should probably (optionally?) include transaction identifier in that case.

**Comment by cincuranet** [comment]
I agree. Accidentally I needed that couple days ago and I hacked it together. I'll clean it up and should be ready to go.

**Comment by cincuranet** [comment]
@krilbe Do you think the level should be info or debug?

**Comment by krilbe** [comment]
Best would be to be able to specify from client code - some apps may even need to be able to specify it differently for different SQL commands even in the same transaction. 

If that's too much hassle, then I'd suggest debug. I wouldn't think that it would be a very common situation to want SQL to be logged in production where no debugging is in progress.
