### ISSUE TITLE
DateOnly and TimeOnly in EFCore

### ISSUE THREAD

**Issue by D3coded** [FirebirdSQL/NETProvider#1025]
I'm having an issue with in EFCore 5.0.9 with Firebird EFCore 8.5.4.

When using
``` C#
public partial class Timeentry{ 
    [Column(TypeName="date")]
    public DateOnly Day { get; set; }
}
```
in my model, and try to create a migration i get following error:

The property 'Timeentry.Day' is of type 'DateOnly' which is not supported by the current database provider.

How can i work with DateOnly and TimeOnly using the Firebird EFCore Provider?

**Comment by cincuranet** [comment]
For `DateOnly`/`TimeOnly` you need to use EF Core 6 (and net6.0) together with [_FirebirdSql.EntityFrameworkCore.Firebird_ 9.0+ (currently not RTM)](https://www.nuget.org/packages/FirebirdSql.EntityFrameworkCore.Firebird/9.0.0-alpha3).

**Comment by D3coded** [comment]
Thank you very much
I have now updated the nuget Package to 9.0.0-alpha3 and updated EFCore to 6.0.1, but i **still get the error** when wanting to create a new migration or running my application with the changes i made to my model.

What have i got to look into, fixing that?

Also when trying to scaffold a new DBContext with the tool "dotnet-ef" i get the following error:

> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Storage.TypeMappingSourceDependencies' while attempting to activate 'FirebirdSql.EntityFrameworkCore.Firebird.Storage.Internal.FbTypeMappingSource'.

**Comment by cincuranet** [comment]
> What have i got to look into, fixing that?

Create a small repro.

**Comment by D3coded** [comment]
I've created a repo that you can clone, to try and reproduce it.
https://github.com/D3coded/fbcore_test

**Comment by cincuranet** [comment]
Thanks. Should be fixed now.
