### ISSUE TITLE
I cannot set ConnectionTimeout to be less than 21 seconds

### ISSUE THREAD

**Issue by bogdan-soare** [FirebirdSQL/NETProvider#1029]
I am having an issue setting the connection timeout using this code.
The exception is raised after 21 seconds every time, regardless of the value for the ConnectionTimeout.
I have tried using await fbConn.OpenAsync() with the same results.
I am using .NETFramework 4.8 and FirebirdSql.Data.FirebirdClient 8.5.4.

DateTime dt = DateTime.Now;
try
{
    FbConnection.ClearAllPools();
    FbConnectionStringBuilder fbBuilder = new FbConnectionStringBuilder();
    fbBuilder.DataSource = "11.11.11.11";
    fbBuilder.Database = "test.fdb";
    fbBuilder.ConnectionTimeout = 1;
    fbBuilder.Pooling = false;
    FbConnection fbConn = new FbConnection(fbBuilder.ConnectionString);
    fbConn.Open();
    fbConn.Close();
}
catch (Exception ex)
{
    MessageBox.Show("Timeout:" + (DateTime.Now - dt).TotalSeconds + Environment.NewLine + ex.Message);
}

**Comment by bogdan-soare** [comment]
What does this mean? I always thought that ConnectionTimeout is the time (in seconds) to wait while trying to establish a connection before terminating the attempt and generating an error.

**Comment by cincuranet** [comment]
Your understanding of `ConnectionTimeout` is correct. But unless you're on .NET 5 or newer the timeout is not going to do anything, because there's no direct support for it.
