### ISSUE TITLE
octet_length etc

### ISSUE THREAD

**Issue by PhilPJL** [FirebirdSQL/NETProvider#1040]
Is there any support - along the lines of EntityFramework.DBFunctions - for using functions like octet_length for EntityFramework.Firebird?

**Comment by PhilPJL** [comment]
I've got a solution - https://weblogs.asp.net/Dixin/EntityFramework.Functions#Add_functions_to_entity_model

Add EntityFrameword.Functions Nuget package.

Add

```
    public static class FirebirdFunctions
    {
        [Function(FunctionType.BuiltInFunction, "OCTET_LENGTH")]
        public static int OctetLength(this byte[] _) => Function.CallNotSupported<int>();
    }
```

and

```
    public class TvlAltContext : DbContext
    {
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Conventions.Add(new FunctionConvention(typeof(FirebirdFunctions)));
        }
```

Good to go

```
	Waveforms
		.Where(w => w.RawRecord.MeasurementId == 311)
		.Select(w => w.Values.OctetLength())
		.FirstOrDefault()
		.Dump();
```

**Comment by cincuranet** [comment]
The path you found with `DbFunction` is a good and flexible. option. 

But remember, `EntityFramework.Firebird` is for EF 6 and it is in "maintenance" mode. I would recommend using EF Core.

**Comment by PhilPJL** [comment]
haha - not going to happen.  I've inherited some very ropey old code which would take more effort than I'm willing to make to convert to .net core.
