### ISSUE TITLE
Possibility to define the Collation

### ISSUE THREAD

**Issue by alansbraga** [FirebirdSQL/NETProvider#1050]
It would be great if during the database creation, using Entity Framework, we could define the default collation.

```ModelBuilder``` has a method ```UseCollation```.
But it doesn't work with Firebird.

Another place that we can change the collation it is configuring properties, the object ```PropertyBuilder``` has a method ```UseCollation``` as well.

Thanks!

**Comment by cincuranet** [comment]
@alansbraga How are you creating database with EF Core?

**Comment by alansbraga** [comment]
Hi!
I'm using:
`DBContext.Database.Migrate();`

Is that what you wanted to know?

Thanks!!!

**Comment by cincuranet** [comment]
Yes, that's it.
