### ISSUE TITLE
Firebird 2.5.9 embedded not working on linux

### ISSUE THREAD

**Issue by rKuettel** [FirebirdSQL/NETProvider#1051]
I encountered a Problem while trying to connect to embedded Firebird 2.5.9 on Linux. 
You need to specify a UserId and Password in the connectionstring, else _TrustedAuth_ is used, which is not supported by embedded. 
But when you pass a UserId or Password to the embedded Server, it tries to check those in the security2.fdb. But since Authentication is not set up in embedded mode you get the following error:   
```
Unhandled exception. FirebirdSql.Data.FirebirdClient.FbException (0x80004005): Your user name and password are not defined. Ask your database administrator to set up a Firebird login.
 ---> FirebirdSql.Data.Common.IscException: Your user name and password are not defined. Ask your database administrator to set up a Firebird login.
   at FirebirdSql.Data.Client.Native.StatusVectorHelper.ProcessStatusVector(IntPtr[] statusVector, Charset charset, Action`1 warningMessage)
   at FirebirdSql.Data.Client.Native.FesDatabase.ProcessStatusVector(Charset charset)
   at FirebirdSql.Data.Client.Native.FesDatabase.AttachAsync(DatabaseParameterBufferBase dpb, String database, Byte[] cryptKey, CancellationToken cancellationToken)
   at FirebirdSql.Data.FirebirdClient.FbConnectionInternal.ConnectAsync(CancellationToken cancellationToken)
   at FirebirdSql.Data.FirebirdClient.FbConnectionInternal.ConnectAsync(CancellationToken cancellationToken)
   at FirebirdSql.Data.FirebirdClient.FbConnection.OpenAsync(CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /test/app/Program.cs:line 21
   at Program.<Main>$(String[] args) in /test/app/Program.cs:line 25
   at Program.<Main>(String[] args)
```

In order to fix this problem, I suggest to add an additional check if it is embedded ServerType in the Connect and ConnectAsync Methods:
```cs
public async Task ConnectAsync(CancellationToken cancellationToken = default)
{
  if (!Charset.TryGetByName(_options.Charset, out var charset))
	  throw new ArgumentException("Invalid character set specified.");
  
  try
  {
	  _db = await ClientFactory.CreateDatabaseAsync(_options, cancellationToken).ConfigureAwait(false);
	  var dpb = BuildDpb(_db, _options);
	  if (string.IsNullOrEmpty(_options.UserID) && string.IsNullOrEmpty(_options.Password) && _options.ServerType == FbServerType.Default)
	  {
		  await _db.AttachWithTrustedAuthAsync(dpb, _options.Database, _options.CryptKey, cancellationToken).ConfigureAwait(false);
	  }
	  else
	  {
		  await _db.AttachAsync(dpb, _options.Database, _options.CryptKey, cancellationToken).ConfigureAwait(false);
	  }
  }
  catch (IscException ex)
  {
	  throw FbException.Create(ex);
  }
}
``` 
Like this you don't need to specify a UserId and Password in the connection string when connecting to Firebird embedded.

**Comment by mrotteveel** [comment]
> That's not correct. Auth still applies in Embedded

To clarify: in Firebird 2.5 and earlier on Linux, authentication against the security database is applied even in Embedded mode. In Firebird 3.0 and higher, authentication against the security database is no longer used for Embedded mode

**Comment by rKuettel** [comment]
> It's just that with Embedded any combination with username/password works (even SYSDBA).

But when I use any combination of username/password I get the Error described in the Issue and therefore can't connect to the Database.

**Comment by cincuranet** [comment]
As Mark pointed out on with 2.5 and Linux (I missed you're running on Linux) the security DB is used.

**Comment by rKuettel** [comment]
This means, the connection should work when I set up a User and Password with gsec, right?
Because I tried that but still got the same error.

The only way I managed to establish connection was without using a username/password which required the suggested change.

**Comment by cincuranet** [comment]
> This means, the connection should work when I set up a User and Password with gsec, right?

Yes. Or `SYSDBA`/`masterkey` (which in FB2.5 was available by default).

**Comment by rKuettel** [comment]
Using `SYSDBA`/`masterkey` or any other user I set up caused the same error.

**Comment by cincuranet** [comment]
It's better if you take this into [_firebird-support_ list](https://firebirdsql.org/en/mailing-lists/).

**Comment by rKuettel** [comment]
I just found another solution for my Problem. 
Setting the environment variables ISC_USER and ISC_PASSWORD and using those credentials solved my problem.

But I'm still a bit confused why it also worked when passing no User/Pass (using my changes)

But anyway thanks for your time and help :)
