### ISSUE TITLE
Increase pagesize of CREATE DATABASE command to 16384 in order to create bigger indices

### ISSUE THREAD

**Issue by onidio** [FirebirdSQL/NETProvider#1056]
Hi,
I played with asp.net core Identity provider and wanted to use firebird (FirebirdSql.EntityFrameworkCore.Firebird) instead of sql server.
When i tried to generate database from scratch, it failed as it could not create indices on VARCHAR(128) fields, due to too small default page size of 4096 of create database statement.
This is easily mitigated by using larger page size of 16384.
This mechanism has already been implemented in "EntityFramework.Firebird" but not in "FirebirdSql.EntityFrameworkCore.Firebird".

**Comment by cincuranet** [comment]
Good idea. The default 4k doesn't make much sense nowadays, especially for EF Core.
