### ISSUE TITLE
.NET 7 EF core support

### ISSUE THREAD

**Issue by PhilPJL** [FirebirdSQL/NETProvider#1077]
Hi,

I just tried creating a test app using .NET 6 + EF 6 core + FirebirdSql.EFCore.Firebird 9.0.2, which works fine.

When updating to .NET 6 (or .NET 7 RC2) + EF 7 RC2 I get one of these exceptions depending on which combination of RC2 packages I have

with Microsoft.EntityFrameworkCore.Relational 6

> Method 'get_QueryProvider' in type 'Microsoft.EntityFrameworkCore.Storage.Internal.RelationalDatabaseFacadeDependencies' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.

or Microsoft.EntityFrameworkCore.Relational 7

> Method not found: 'System.Collections.Generic.IList`1<Microsoft.EntityFrameworkCore.Metadata.Conventions.IModelInitializedConvention> Microsoft.EntityFrameworkCore.Metadata.Conventions.ConventionSet.get_ModelInitializedConventions()'.

Known issue?

**Comment by cincuranet** [comment]
Yes, that's expected. You can't mix and match EF Core versions with provider.

**Comment by PhilPJL** [comment]
Hi,

the first exception was because I was mixing versions, so probably expected.
The second one is using:
![image](https://user-images.githubusercontent.com/271656/197573999-ca53110c-152f-4e41-8bab-a729749397cf.png)

and 
![image](https://user-images.githubusercontent.com/271656/197574267-03ba897e-ab17-4d21-81b5-569586716bc6.png)

Is that still expected?  In which case I need to wait for an update?

**Comment by cincuranet** [comment]
Still. You'd need provider that is EFCore7 compatible (and that's not 9.0.2).
