### ISSUE TITLE
.NET 7 + EF Core 7 support

### ISSUE THREAD

**Issue by cincuranet** [FirebirdSQL/NETProvider#1083]
Rough plan:
- [x] .NET 7 provider targeting
- [x] EF Core 7 build
- [x] EF Core 7 features
- [x] EF Core 7 tests

Extra:
- [ ] #1059

**Comment by ErikEJ** [comment]
Just FYI, EF Core 7 targets .NET 6

**Comment by Ionut27** [comment]
any chance to see this year a preview version net7 compatible?

**Comment by cincuranet** [comment]
Preview version of what? ADO.NET provider or EF Core provider?

**Comment by Ionut27** [comment]
as title above EF Core 7 support

**Comment by Igor-ZA** [comment]
Hi!
When NET7 support will release?
thx

**Comment by cincuranet** [comment]
No hard ETA yet.

**Comment by Igor-ZA** [comment]
Hi!
Why is the upgrade to .NET 7 taking so long?
It's almost pointless to do the task now, as .NET 8 is just around the corner.

**Comment by cincuranet** [comment]
I'm working on it as my free time permits. But you're more than welcome to sponsor this issue and/or become FF sponsor.

**Comment by fdcastel** [comment]
@cincuranet there is already any work done in this direction?

If yes, could you please push it in another branch in this repository?

I'm asking this because I'm in dire need of some features which are present only in EF Core 7.0. I could contribute with PRs, if desired. 

Currently using `FirebirdSql.EntityFrameworkCore.Firebird` 9.1.1 with EF Core 7.0 gives me the following error:

```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IList`1<Microsoft.EntityFrameworkCore.Metadata.Conventions.IModelInitializedConvention> Microsoft.EntityFrameworkCore.Metadata.Conventions.ConventionSet.get_ModelInitializedConventions()'.
   at FirebirdSql.EntityFrameworkCore.Firebird.Metadata.Conventions.FbConventionSetBuilder.CreateConventionSet()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RuntimeConventionSetBuilder.CreateConventionSet()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   ...
```

**Comment by cincuranet** [comment]
[This](https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/tree/ef7) branch.

**Comment by fdcastel** [comment]
@cincuranet this branch appears to be working fine. The error mentioned above doesn't occur. 🙌 

Also, I spent the last hours working with it and nothing exploded on my face. 

That said... it would be possible for you to publish it _as is_ as a pre-release version (e.g. `9.2-beta`)? 

I know it is a far cry from having all checks from your original "rough plan". But it seems to me it would be useful for anyone anxious to use EF Core 7.0 -- _and, judging by the reactions of this issue, I'm not the only one. 😉_

**Comment by cincuranet** [comment]
That's a sane idea, with the recent TPC finishes, it makes sense to have some pre-release version. Enjoy https://www.nuget.org/packages/FirebirdSql.EntityFrameworkCore.Firebird/9.2.0-alpha1.

**Comment by ErikEJ** [comment]
I will get it added to EF Core Power Tools!

**Comment by cincuranet** [comment]
Living on the edge, right? ;)

**Comment by ErikEJ** [comment]
It is only the reverse engineering part that is used...

**Comment by cincuranet** [comment]
Done via a86a6f94d006316d2d4d64a1a1b8c9b19bafae07.
