### ISSUE TITLE
Upgraded from ver 8.5.4 to 9.x.x and now FbDataReader.Close throws exception 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by Bubak** [FirebirdSQL/NETProvider#1085]
at FirebirdSql.Data.Logging.LogMessages.TransactionCommitted
The last message in the log is 'Committing transaction'.
Any simple select with the implicit transaction.
FbLogLevel.Trace
I need SQL in the log so I can use Trace or Debug level but both levels try to log transaction actions too.

**Comment by cincuranet** [comment]
Provide a test case.

**Comment by Bubak** [comment]
https://github.com/Bubak/FbTransactionLoggingTest

app creates log file in exe directory

in Program.cs 
at line 9 replace CONNECTION STRING
at line 12 replace COMMAND TEXT

Exception at line 17
