### ISSUE TITLE
How to set charset for win1252 in C# ?

### ISSUE THREAD

**Issue by rdrgbaioco** [FirebirdSQL/NETProvider#1086]
Every time I try to put in the connection string (Charset=win1252, Chartset=windows_1252), it doesn't work, but Charset=ISO8859_1 works, what am I doing wrong?

![image](https://user-images.githubusercontent.com/85860664/202914724-ebf3af09-ac49-4ce5-93d5-bfb44a636c7b.png)

**Comment by cincuranet** [comment]
Using `win1252` is correct. But you very likely forgot to add `CodePagesEncodingProvider`. [Link](https://www.tabsoverspaces.com/id/233650).
