### ISSUE TITLE
How to set readonly access mode?

### ISSUE THREAD

**Issue by Rainson12** [FirebirdSQL/NETProvider#1089]
Hi,
is there a way to set the access mode to readonly when setting up the connection while using up ef core? I can see that there is some method to set the accessMode for the FbConfigurationService (https://github.com/FirebirdSQL/NETProvider/blob/ebd58c427de8fcdc3c5b08541a450dc09831e023/src/FirebirdSql.Data.FirebirdClient/Services/FbConfiguration.cs#L616)  but I am unable to access it when using ef dbcontext wiring?

**Comment by cincuranet** [comment]
Either the database is in RO mode, which you can set using the `FbConfiguration` or the you have RO transaction. There's nothing that relates to connection.

**Comment by Rainson12** [comment]
thanks for pointing out. worked
