### ISSUE TITLE
Writing string via EF contains unexpected bytes

### ISSUE THREAD

**Issue by stormcrow79** [FirebirdSQL/NETProvider#1093]
Inserting or updating a string field using Entity Framework results in unexpected byte sequences when all of the following conditions are met:

- the connection string specifies an encoding other than UTF-8
- the entity contains a string property where the database column has the character set 'NONE'
- the entity also contains a computed property of any type

**Environment**
- Firebird 4.0.2 x64 on Windows
- .NET Framework 4.8
- EntityFramework 6.4.4
- FirebirdClient 9.1.1

```
create table tests (
  id int generated by default as identity primary key,
  name varchar(50) character set none,
  modified timestamp computed by (localtimestamp));

var connectionString = "DataSource=localhost;User=SYSDBA;Password=********;Database=employee;Character Set=WIN1252;";

context.Tests.Add(new Test() { Name = "O\u2019Grady" });
```

Expected outcome: name contains "O’Grady" with a curly apostrophe
Actual outcome: name contains "Oâ€™Grady" (the UTF-8 bytes for U+2019)

This appears to be caused by the explicit use of UTF-8 in `GenerateReturningSql`.

```
if (param.FbDbType == FbDbType.VarChar || param.FbDbType == FbDbType.Char)
  startBlock.Append(" CHARACTER SET UTF8");
```
Removing this line seems to resolve this particular problem.

NOTE: This problem does NOT occur using Firebird 2.5.9.

**Comment by stormcrow79** [comment]
FYI @wyldphyre

**Comment by stormcrow79** [comment]
@cincuranet i've added our repro at https://github.com/stormcrow79/FirebirdSql.Data.FirebirdClient/tree/test-encodings

we're still trying to get the test suite running to investigate further.

**Comment by cincuranet** [comment]
EF6 provider is in maintenance/legacy mode. I do not plan releasing (except for security fixes, if any) more versions of this provider. If you feel like creating a good, quality, complete PR, I will consider merging it.

**Comment by stormcrow79** [comment]
Hi @cincuranet, thanks for your feedback. We'll look into creating a PR for EF6.

Meantime we've just tested the EF Core provider and it does seem to behave the same way.

**Comment by cincuranet** [comment]
Create issue with test case for EF Core, please.
