### ISSUE TITLE
Plase write manual about connection string for Entity Frameworc Core

### ISSUE THREAD

**Issue by Andrey-2021** [FirebirdSQL/NETProvider#1100]
Hi!
Plase write manual about connection string for Entity Frameworc Core

You exaple 
[https://github.com/FirebirdSQL/NETProvider/blob/master/docs/entity-framework-core.md](https://github.com/FirebirdSQL/NETProvider/blob/master/docs/entity-framework-core.md)

1) how I must write file name,
if it in folder 
c:\firefox\testdataz.fdb ?

the string:
using (var db = new MyContext("DataSource=localhost;Database=C:\\firedird\\testdataz.fdb;User=SYSDBA;Password=1234"))

don't work

2) where must be  demo.fdb file on you example?

3) How config connection string 
to method Database.EnsureCreated()  work?

Thanks!

**Comment by cincuranet** [comment]
Connection string for EF Core is same as connection string for FirebirdClient. 

1. Path from server's POV. I suggest reading about some Firebird server basics.
2. In Firebird's default folder. Or you can specify full path.
3. Any valid connection string works.

BTW "don't work" is not a good description of problem.
