### ISSUE TITLE
Unicode problems

### ISSUE THREAD

**Issue by gilsonjoanelo** [FirebirdSQL/NETProvider#1103]
Hi,
I'm using Google Translate

I have a problem turning off Unicode in Firebird connected EF Core Net 6.0. Currently there is an option in which it is possible to define the String property, this is OK. Even a PR suggested by me was incorporated into the project.

However, when entering the FbStringTypeMapping class, the unicode parameter is always true. This makes the code behave like Unicode, however our code is not unicode.

Is there any way to globally turn this off in Firebird Provider for Net Core?

**Comment by cincuranet** [comment]
Do you have a code to show the behavior?

**Comment by gilsonjoanelo** [comment]
This is the entity configuration
`public class ArtigoConfiguration : IEntityTypeConfiguration<Artigo>
		{
			public void Configure(EntityTypeBuilder<Artigo> builder)
			{
				var nomes = new ArtigoNomesColuna();
				var tabelaNome = new ArtigoNomes().TabelaNome;
				builder.HasKey(p => p.ID);
				builder.Property(p => p.ID).HasColumnName(nomes.ID).HasColumnType("INTEGER").IsRequired();
				builder.Property(p => p.ArtigoCategoriaID).HasColumnName(nomes.ArtigoCategoria).HasColumnType("INTEGER");
				builder.Property(p => p.SiteID).HasColumnName(nomes.Site).HasColumnType("INTEGER");
				builder.Property(p => p.UsuarioAdministrativoID).HasColumnName(nomes.UsuarioAdministrativo).HasColumnType("INTEGER");
				builder.Property(p => p.FotoID).HasColumnName(nomes.Foto).HasColumnType("INTEGER");
				builder.Property(p => p.Titulo).HasColumnName(nomes.Titulo).HasColumnType("VARCHAR(80)").HasMaxLength(80).IsUnicode(false);
				builder.Property(p => p.Conteudo).HasColumnName(nomes.Conteudo).HasMaxLength(2147483647).IsUnicode(false);
				builder.Property(p => p.ArtigoTipoID).HasColumnName(nomes.ArtigoTipo).HasColumnType("INTEGER");
				builder.Property(p => p.Autor).HasColumnName(nomes.Autor).HasColumnType("VARCHAR(150)").HasMaxLength(150).IsUnicode(false);
				builder.Property(p => p.DataInclusao).HasColumnName(nomes.DataInclusao).HasColumnType("TIMESTAMP");
				builder.Property(p => p.DataAlteracao).HasColumnName(nomes.DataAlteracao).HasColumnType("TIMESTAMP");
				builder.Property(p => p.Resumo).HasColumnName(nomes.Resumo).HasColumnType("VARCHAR(195)").HasMaxLength(195).IsUnicode(false);
				builder.Property(p => p.Destaque).HasColumnName(nomes.Destaque).IsRequired().HasColumnType("SMALLINT");
				builder.Property(p => p.Ativo).HasColumnName(nomes.Ativo).IsRequired().HasColumnType("SMALLINT");
				builder.Property(p => p.TotalCliques).HasColumnName(nomes.TotalCliques).HasColumnType("INTEGER").IsRequired();
				builder.Property(p => p.ExibirSiteDataCempro).HasColumnName(nomes.ExibirSiteDataCempro).IsRequired().HasColumnType("SMALLINT");


				builder.ToTable(tabelaNome);
			}
		}`

When run, in the mentioned class the unicode property is always true, this causes unnecessary conversion and forces cast to UTF8 as exemplified in the code below extracted from the log.

[202304261426.log](https://github.com/FirebirdSQL/NETProvider/files/11335984/202304261426.log)

**Comment by gilsonjoanelo** [comment]
I am attaching two files, one with the code and one with the log

[202304261426.log](https://github.com/FirebirdSQL/NETProvider/files/11336000/202304261426.log)

[Artigo.cs.txt](https://github.com/FirebirdSQL/NETProvider/files/11336005/Artigo.cs.txt)

Even with the definition of the property IsUnicode(false), it is always considering Unicode(true). which causes the problem that appears in the log, all the queries are transformed into the wrong Charset. the Database Charset is Win1252. We do not use Unicode in this database. I don't know if there is any way to force FbOptions to respect Unicode(false)

**Comment by cincuranet** [comment]
You can play with [this](https://github.com/FirebirdSQL/NETProvider/blob/master/src/FirebirdSql.EntityFrameworkCore.Firebird/Infrastructure/FbDbContextOptionsBuilder.cs#L33). But it will get you only so far. There's few places in EF Core provider with UTF-8 encoding assumption and at the moment I don't have plans to have support for charsets other than UTF-8, mainly because of resource/cost.
