### ISSUE TITLE
FBStreamingBackup only backs up data

### ISSUE THREAD

**Issue by iWhacko** [FirebirdSQL/NETProvider#1108]
Our application connects to a firebird database on the local network.

Some operators have the ability to make a backup from the application. However we found that the backup seems to be incomplete.

When using the command line tools to import the backup into a new database, an message appears asking for "disk2" of the backup. 
Checking the database, we noticed it does not contain our stored procedures, functions triggers. etc.

However, FBStreamingBackup completed with a success message in our application.

We would like to know if this is a bug, a limitation on the api, or do we need to apply some more parameters to our call:

```
            var backup = new FbStreamingBackup(connectionStr);
            backup.OutputStream = outputStream;
            backup.ExecuteAsync();
```

**Comment by cincuranet** [comment]
You're missing `await` on the last line.

**Comment by iWhacko** [comment]
You are right, this was a quick write up, we tried it the synchronised way to with execute(); But  it has the same result
