### ISSUE TITLE
is longer than Firebird's 31 characters limit for object names.

### ISSUE THREAD

**Issue by ddisante** [FirebirdSQL/NETProvider#1127]
Hi,
I have this error in my C# ASP .Net project with Update-Database EF command for a ForeignKey, my configuration is:

- .Net 4.8;
- Firebird 4.0.3.2975:
- EF6;
- EntityFramework.Firebird 9.1.1;

All Nuget packages are up to date.

In firebird.conf and database.conf I've enable support for 63 char.

I tried with Flamerobin and DBeaver to create object with name over 31 char and no error issue.

Thanks in advance.

**Comment by cincuranet** [comment]
EF6 provider here is in maintenance/legacy mode here (see https://groups.google.com/g/firebird-net-provider/c/_0Hwoh5XG_I). If somebody feels like tackling this with good PR, it will be reopened.
