### ISSUE TITLE
EF Core 8 support

### ISSUE THREAD

**Issue by cincuranet** [FirebirdSQL/NETProvider#1129]

**Comment by michaelmairegger** [comment]
Any news on that feature

**Comment by AdamWyzgol** [comment]
Can you look on that PR? https://github.com/FirebirdSQL/NETProvider/pull/1153 should allow to use with .net 8 projects and EF Core 8

**Comment by AdamWyzgol** [comment]
@cincuranet  I pushed one more commit to my fork, maybe it's ok now but looks like to run actions there is need to have custom runner? I think that commit should make possible to pass all tests from my closed PR https://github.com/PaxillusIT/NETProvider/commit/4f33ddc59eb4da2ffd45b7c9460cbb608489f857

**Comment by AdamWyzgol** [comment]
Ok, I make test working in my fork but looks like now it's failing on EF6 tests

**Comment by cincuranet** [comment]
👀 https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/tree/ef8

**Comment by cincuranet** [comment]
@abraluve Firebird provider for EF Core 8 was not yet released (and this issue is still open, as you can see), so I guess you're using older provider version with newer EF Core, which is obviously unsupported scenario.

**Comment by abraluve** [comment]
Yea thats rights, I am just reporting what I found :)) I read other issues and I see its not yet released :)

**Comment by Igor-9309** [comment]
Hi!

Any news on that feature?

thx

**Comment by abraluve** [comment]
@Igor-9309 compile on your own not released repo from cincuranet above. Its still in dev however it can be used on .NET 8 at least.

**Comment by cincuranet** [comment]
https://www.nuget.org/packages/FirebirdSql.EntityFrameworkCore.Firebird/11.0.0-alpha1

**Comment by cincuranet** [comment]
Done via f2a55392a1a04a745b364a8edb989086bd579989.

**Comment by Igor-9309** [comment]
Hi!

When will the new release version of the package be ready?

Thanks

**Comment by cincuranet** [comment]
It was released couple of minutes ago: https://github.com/FirebirdSQL/NETProvider/releases/tag/EFCore-11.0.0.0

**Comment by Igor-9309** [comment]
THX 👍🍺🍺🍺
