### ISSUE TITLE
EntityFrameworkCore Scaffolding: FbDatabaseModelFactory does not reflect NULL_FLAG from Domains

### ISSUE THREAD

**Issue by bgrauer-atacom** [FirebirdSQL/NETProvider#1131]
When using EfCore Scaffolding (Reverse Engineering) not null is interpreted not correct when using Firebird Domains.

-------------------

I suppose the query in [FbDatabaseModelFactory](src/FirebirdSql.EntityFrameworkCore.Firebird/Scaffolding/Internal/FbDatabaseModelFactory.cs)

https://github.com/FirebirdSQL/NETProvider/blob/f169563ec05067c55974d2dfe09ff4f64cfd05d9/src/FirebirdSql.EntityFrameworkCore.Firebird/Scaffolding/Internal/FbDatabaseModelFactory.cs#L149

should be
``` SQL
COALESCE(COALESCE(RF.RDB$NULL_FLAG, F.RDB$NULL_FLAG), 0) as NOT_NULL,
```

but i donw know if this has any inpacts regarding bckwards comaptibility.

**Comment by cincuranet** [comment]
Probably minimal impact on backwards compat. It's a bug fix. Do you care to create PR?

**Comment by bgrauer-atacom** [comment]
Shure. Want me to write a test?

**Comment by cincuranet** [comment]
Test would be lovely.
