### ISSUE TITLE
Scaffolding error with Firebird 2.5 with Numeric columns

### ISSUE THREAD

**Issue by lvalgimigli** [FirebirdSQL/NETProvider#1142]
When i try to scaffold a Firebird 2.5 Database i get this error:  
 **Could not find type mapping for column 'XXXXXX' with data type 'NUMERIC(4,2)'. Skipping column.**  
My project references are:  FirebirdSql.EntityFrameworkCore.Firebird (10.0.0),  EntityFramework.Firebird(10.0.0) ,   
EntityFramework.Firebird (10.0.0)

**Comment by lvalgimigli** [comment]
For my project i have used the last stable version of all libraries (10.0.0), have you a new version?

**Comment by cincuranet** [comment]
Dupe of #1141.
