### ISSUE TITLE
Build FirebirdSql.Data.FirebirdClient for  netstandard2.1

### ISSUE THREAD

**Issue by MagGr** [FirebirdSQL/NETProvider#1144]
Hello!

I can't build FirebirdSql.Data.FirebirdClient from latest version of NETProvider   for netstandard2.1. 
This target framework use С# language version 10.0, and I have compile errors in 
Error	CS8936	Feature 'unsigned right shift' is not available in C# 10.0. Please use language version 11.0 or greater.

Could you please recommend me what is version of NETProvider should I use for netstandard2.1.?

**Comment by cincuranet** [comment]
https://github.com/FirebirdSQL/NETProvider/blob/867fa99dd5752de942ad50b91d8b9e6305fe35ef/src/Directory.Build.props#L3
