### ISSUE TITLE
Firebird 3.0 connection issues

### ISSUE THREAD

**Issue by matasarei** [FirebirdSQL/NETProvider#1151]
**Plugin version: 10.0.0**

Hey!

Trying to connect to a local Firebird 3.0 database:
```
            FbConnectionStringBuilder connectionStringBuilder = new FbConnectionStringBuilder()
            {
                DataSource = "127.0.0.1",
                Port = 3050,
                Database = "*****",
                UserID = "REMOTEUSER",
                Password = "*********",
            };

            connection = new FbConnection(connectionStringBuilder.ConnectionString);
            connection.Open();
```
Exception:
```
IscException: Your user name and password are not defined. Ask your database administrator to set up a Firebird login.
```
firebird.conf:
```
ServerMode = SuperClassic
DefaultDbCachePages = 1500
FileSystemCacheThreshold = 2M
TempBlockSize = 2M
TempCacheLimit = 3000M
AuthServer = Legacy_Auth, Srp, Win_Sspi
AuthClient = Legacy_Auth, Srp, Win_Sspi
UserManager = Legacy_UserManager, Srp
WireCrypt = Enabled 
RemoteServicePort = 3050
LockMemSize = 40M
LockHashSlots = 49999
```

Tried my creds with [DB Explorer](https://marketplace.visualstudio.com/items?itemName=marinv.vscode-db-explorer-firebird) and all seems fine. What can be wrong here?

UPD:
Likely I need, will try and report later:
```
create user <youruser> password '<password>' using plugin srp;
```

**Comment by mrotteveel** [comment]
This sounds more like a support question, which would be more suitable for https://groups.google.com/g/firebird-net-provider.

In any case, likely your user is a Legacy_Auth user, which is not supported by the Firebird ADO.NET provider when connecting to Firebird 3.0 or higher. Your user needs to be a Srp user.
