### ISSUE TITLE
Firebird 5.0

### ISSUE THREAD

**Issue by andvl-mail-ru** [FirebirdSQL/NETProvider#1159]
Hi.

After i update my Server From Firebird 4 to Firebird 5.0
output parameters of FbCommand no longer return values (SERVER return values):

CommandText = "insert into demo values (@id, 'FooBar') returning *";  = OK
CommandText = "update or insert into demo values (@id, 'FooBar') returning *"; = EMPTY

Short sample code:

using (var connection = new FbConnection("database=localhost:demo;user=sysdba;password=masterkey"))
{
    connection.Open();

    using (var command = connection.CreateCommand())
    {
        command.CommandText = "update or insert into demo values (@id, 'FooBar') returning * ";

        var pID = command.CreateParameter();
        pID.ParameterName = "@id";
        pID.FbDbType = FbDbType.Integer;
        pID.Direction = System.Data.ParameterDirection.InputOutput;

        command.Parameters.Add(pID);

        var res = command.ExecuteNonQuery();

        Debug.Print(pID.Value?.ToString());
        
    }
};

**Comment by cincuranet** [comment]
That's [described and documented behavior](https://github.com/FirebirdSQL/NETProvider/issues/1066).
