### ISSUE TITLE
Add public getter for FbCommand._namedParameters

### ISSUE THREAD

**Issue by dant02** [FirebirdSQL/NETProvider#1161]
Hi,

would it be feasible to add public getter to _namedParameters field in FbCommand ?

My use case is to get names of the parameters for a query which I do not know beforehand.

I'll be happy to create PR for it.

Thank you
Best regards
Daniel Trubač

**Comment by cincuranet** [comment]
Yeah. I don't see a reason why not. So go ahead with your PR.
