### ISSUE TITLE
Add hook to tweak transaction options when using System.Data.IsolationLevel interface

### ISSUE THREAD

**Issue by krilbe** [FirebirdSQL/NETProvider#1172]
When using frameworks that support ADO but are agnostic about what the underlying database is, and the framework is creating transactions using only `System.Data.IsolationLevel` transaction settings, it's currently impossible to specify Firebird specific transaction options, e.g. `WAIT`.

Please add a hook or settings to tweak how the Firebird provider maps `System.Data.IsolationLevel` to Firebird transaction settings.

For example, at the end of `FbTransaction.BuildTpb()`, before returning, you could add something like this:

```csharp
if (OptionsHook != null)
{
    options = OptionsHook(options, IsolationLevel);
}
```

And add the public static property `OptionsHook` as follows:

```csharp
public static Func<FbTransactionOptions, IsolationLevel, FbTransactionOptions> OptionsHook { get; set; } = null;
```

In the app code using that ADO framework, this would for example allow to specify `WAIT` in the callback:

```csharp
FbTransaction.OptionsHook = (opt, il) => {
    if (il == IsolationLevel.ReadCommitted)
    {
        opt.TransactionBehavior &= ~FbTransactionBehavior.NoWait;
        opt.TransactionBehavior |= FbTransactionBehavior.Wait;
    }
    return opt;
};
```

**Comment by cincuranet** [comment]
1. That's very non-standard.
2. The framework should provide a way for you to customize transaction (i.e. EF Core allows that).

**Comment by krilbe** [comment]
I agree about your second point. About the first point, yes, perhaps.

But I do think that your choice to map `System.Data.ReadCommitted` to use `NoWait` seems very arbitrary, and that this should really be up to us who use the provider to make that choice. Same goes for `RecVersion`/`RecVersion`.

So, it seems like a fair idea to provide some means to at least choose between `Wait`/`NoWait` and between `RecVersion`/`RecVersion`. One static property each? I.e.

```csharp
public static bool UseWait { get; set; } = false;
public static bool UseRecVersion { get; set; } = true;
```

FWIW I have an open case with the framework provider too.

**Comment by krilbe** [comment]
We might be willing to sponsor implementation of those two options (or at least the `Wait`/`NoWait` option, which is really the one we need.
