### ISSUE TITLE
EnableRetryOnFailure not provided for this driver

### ISSUE THREAD

**Issue by victorvilella** [FirebirdSQL/NETProvider#1186]
My App has connection with multiple databases with same structure (tables, stored procedures, triggers, etc).

When FB connection is lost I can't easily rebuild my connection pool. When it occurs the only way to resolve this problem is restart entire application. 

Looking in my project, I did not found `EnableRetryOnFailure()` on `OnConfiguring()` method inside my context.

I'm using .NET Core 8 with EFCore 8.

Did I missed some detail? Thanks in advance.

**Comment by victorvilella** [comment]
Alright. I'll try to make a PR about this feature someday.

Thanks.

**Comment by willibrandon** [comment]
I just bumped into this while writing a .NET Aspire integration for the EF Core provider. I would like to configure retries for the `DbContext` by implementing an `EnrichFirebirdDbContext` extension method, which would leverage `EnableRetryOnFailure` if it was available.

**Comment by willibrandon** [comment]
> I just bumped into this while writing a .NET Aspire integration for the EF Core provider. I would like to configure retries for the `DbContext` by implementing an `EnrichFirebirdDbContext` extension method, which would leverage `EnableRetryOnFailure` if it was available.

Never mind, I see that I can configure the DbContext with an execution strategy myself.
