### ISSUE TITLE
Ef Core 8 Error Method ExecuteSql

### ISSUE THREAD

**Issue by ViperTecCorporation** [FirebirdSQL/NETProvider#1199]
Olá estou tendo este problema ao executar este sql atraves do entity framework core, isto não ocorria no .Net 6 to testando para migrar o projeto, tem alguma dica de solução?

Hello, I'm having this problem when running this sql through the entity framework core, this didn't happen in .Net 6, I'm testing to migrate the project, do you have any solution tips?

firebird 4.0 estou usando. 

con.Database.ExecuteSql($"ALTER SEQUENCE \"RDB$2\" RESTART WITH {ultIdPersons};");
con.SaveChanges();

{"Dynamic SQL Error\r\nSQL error code = -104\r\nToken unknown - line 1, column 37\r\n?"}

**Comment by ViperTecCorporation** [comment]
And another question, I have a legacy database that I need to maintain due to an integration with our other software, the database engine is Firebird 2.5 in version 6 of .Net core, I was able to use the Where method of the entity migrating the project to test in version 8 I get the following error

{"Dynamic SQL Error\r\nSQL error code = -104\r\nUnexpected end of command - line 3, column 269"}


Is there anything you can do to mitigate this problem?

**Comment by cincuranet** [comment]
> And another question, I have a legacy database that I need to maintain due to an integration with our other software, the database engine is Firebird 2.5 in version 6 of .Net core, I was able to use the Where method of the entity migrating the project to test in version 8 I get the following error

Firebird 2.5 is not supported. Unless you can replicate it on at least 3.0, you are on your own. But I'm happy to take PR.

> Hello, I'm having this problem when running this sql through the entity framework core, this didn't happen in .Net 6, I'm testing to migrate the project, do you have any solution tips?

`ExecuteSql` is not available on EF Core 6, so I'm not sure what you called before. But the problem is that `ALTER SEQUENCE` needs literal, not parameter.

**Comment by ViperTecCorporation** [comment]
thanks
