### ISSUE TITLE
Wrong generate SQL statement for the stored procedure [DNET723]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#232]
Submitted by: Denis Maslov (denmpei)

Votes: 3

Good day\!

When I try execute simple procedure over EF, i got the next error: "FirebirdSql\.Data\.FirebirdClient\.FbException: Dynamic SQL Error SQL error code = \-204 Implementation limit exceeded \.\.\." 
In the end, I found that the problem in the wrong EF generation sql statement\.

Text procedure \(Firebrd\):
procedure B\_IMP\_I\_REESTR \( 
    IDUSER integer, 
    IMPMODE integer, 
    IDGEN integer, 
    IDPARENT integer, 
    IDTCH integer, 
    NOMER varchar\(15\), 
    SBORNIK integer, 
    NAME varchar\(250\), 
    VIX\_DAN blob sub\_type 0 segment size 80, 
    ISSYSTEM integer, 
    POKAZ varchar\(8\), 
    GOD integer, 
    RABMAT integer, 
    IDGROUP integer, 
    IDPODGROUP integer, 
    IDTYPE integer, 
    ORDERVIEW integer, 
    CREATEDATE date, 
    AUTHOR varchar\(250\), 
    NORM\_GUID varchar\(100\), 
    INSTALL\_GUID varchar\(100\), 
    INDEX\_YEAR integer, 
    INDEX\_MONTH integer, 
    INDEX\_ORGNAME varchar\(250\), 
    INDTYPE varchar\(50\)\) 
returns \( 
    ID integer\) 
\.\.\.

Text procedure \(EF generate\):
SELECT 
1 AS "C1", 
"A"\."ID" AS "ID" 
FROM "B\_IMP\_I\_REESTR"\(CAST\(@IDUSER AS INT\), CAST\(@IMPMODE AS INT\), CAST\(@IDGEN AS INT\), CAST\(@IDPARENT AS INT\), CAST\(@IDTCH AS INT\), CAST\(@NOMER AS VARCHAR\(8191\)\), CAST\(@SBORNIK AS INT\), CAST\(@NAME AS VARCHAR\(8191\)\), CAST\(@VIX\_DAN AS BLOB SUB\_TYPE BINARY\), CAST\(@ISSYSTEM AS INT\), CAST\(@POKAZ AS VARCHAR\(8191\)\), CAST\(@GOD AS INT\), CAST\(@RABMAT AS INT\), CAST\(@IDGROUP AS INT\), CAST\(@IDPODGROUP AS INT\), CAST\(@IDTYPE AS INT\), CAST\(@ORDERVIEW AS INT\), CAST\(@CREATEDATE AS TIMESTAMP\), CAST\(@AUTHOR AS VARCHAR\(8191\)\), CAST\(@NORM\_GUID AS VARCHAR\(8191\)\), CAST\(@INSTALL\_GUID AS VARCHAR\(8191\)\), CAST\(@INDEX\_YEAR AS INT\), CAST\(@INDEX\_MONTH AS INT\), CAST\(@INDEX\_ORGNAME AS VARCHAR\(8191\)\), CAST\(@INDTYPE AS VARCHAR\(8191\)\)\) AS "A" 

For example, why INDTYPE varchar\(50\) \-\> CAST\(@INDTYPE AS VARCHAR\(8191\)\) ???

Regards, Maslov Denis\.

**Comment by cincuranet** [comment]
EF6 provider here is in maintenance/legacy mode here (see https://groups.google.com/g/firebird-net-provider/c/_0Hwoh5XG_I). If somebody feels like tackling this with good PR, it will be reopened.
