### ISSUE TITLE
performance: round-trip/sql invocation cost [DNET280]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#291]
Submitted by: Vasily Kabanov (vaso)

Attachments:
[Program.cs](https://github.com/FirebirdSQL/jira-attachments/raw/main/DNET/DNET-280/12277_Program.cs)
[IbxSpeedTest.dpr](https://github.com/FirebirdSQL/jira-attachments/raw/main/DNET/DNET-280/12278_IbxSpeedTest.dpr)

Votes: 1

I tried populating simple test table with parameterized insert statement\. It was very slow \(\~270 rows/second\)\. Processor utilization was 15\-40%, 60\-70% of which \- in kernel \(which to me was a sign of something unproductive going on\)\.
1st, I suspected query re\-parsing to be a problem and packaged insert into a SP, no luck\.
2nd, suspected character sets convertions for strings and left only integer parameters, again slow\.
finally, suspected some marshaling or reflection issues and tried \.NET over ODBC\.
Parameterized insert was slow again, but when using stored proc performance went up: 6500 rows/second which is excellent\.

**Comment by cincuranet** [comment]
Closing now in favor of specific performance tasks.
