### ISSUE TITLE
Null reference exception on fbcommand dispose [DNET316]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#327]
Submitted by: Gerdus van Zyl (angelblaze)

Is duplicated by [DNET368](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET368+in%3Atitle)
Is duplicated by [DNET386](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET386+in%3Atitle)

Attachments:
[FirebirdNullExceptionReproduce.zip](https://github.com/FirebirdSQL/jira-attachments/raw/main/DNET/DNET-316/12410_FirebirdNullExceptionReproduce.zip)

Votes: 6

I have been getting the following exception if I close an connection \(or forget to close connection manually\) before explicitly calling \.Dispose\(\) on all FbCommands created \(I now put fbcommand object in a list and dispose of manually before connection close\)\. Which is strange since I can't see where I keep die commands alive beyond the life of the connection\. The part of my program which gives the problem is a database schema upgrade that runs in a background thread\.

Object reference not set to an instance of an object\.

stack trace: 
   at FirebirdSql\.Data\.FirebirdClient\.FbConnectionInternal\.RemovePreparedCommand\(FbCommand command\)
   at FirebirdSql\.Data\.FirebirdClient\.FbCommand\.Release\(\)
   at FirebirdSql\.Data\.FirebirdClient\.FbCommand\.Dispose\(Boolean disposing\)
   at System\.ComponentModel\.Component\.Finalize\(\)

target site:
\{Void RemovePreparedCommand\(FirebirdSql\.Data\.FirebirdClient\.FbCommand\)\}

Commits: FirebirdSQL/NETProvider@f71e5d88383ee1009076cb6591fb93af9a6258ea

**Comment by MarkR-coder** [comment]
I observed the same behavior. I don't know really what caused it in my [case](https://newportbeachconcrete.com/).
