### ISSUE TITLE
Cannot establish a connection in Server Explorer when using Windows authentication [DNET373]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#378]
Submitted by: John Carroll (llorracj)

Depends on [DNET659](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET659+in%3Atitle)

If you attempt to create a connection in Visual Studio using a database which is 
using Windows authentication, you cannot establish the connection\. Everything 
appears to work \- including the "Test Connection" indicating success\. However, 
the OK button is disabled and remains disabled\. It appears DDEX is incompatible 
with Windows authentication since it requires then entry of a user name and 
password\.

**Comment by cincuranet** [comment]
Closing because #1001.
