### ISSUE TITLE
FBValidation does not output any information as to success or failure of a requested Database Validation operation. [DNET399]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#402]
Submitted by: Can A. Course (canacourse)

No exception is thrown either\.

Sample code below\.

  private void ValidateDB\(string Database\)
        \{
            FbConnectionStringBuilder ConnectionString = new FbConnectionStringBuilder\(\);
            ConnectionString\.ServerType = FbServerType\.Embedded;
            ConnectionString\.Database = Database;
            ConnectionString\.UserID = "sysdba";
            ConnectionString\.Password = "dummypassword"; // this is required
            ConnectionString\.Dialect = 3;
            
            try
            \{
                FbValidation DBValidator = new FbValidation\(\);
                DBValidator\.ConnectionString = ConnectionString\.ToString\(\);
                DBValidator\.Options = FbValidationFlags\.SweepDatabase; // or any other FBValidationFlags\.
                DBValidator\.ServiceOutput \+= ServiceOutput;
                DBValidator\.Execute\(\);
            \}
            catch \(Exception e\)
            \{
                Log\.FatalException\("Unable to validate Database", e\);
                Environment\.Exit\(0\);
            \}
           
        \}

  private static void ServiceOutput\(object sender, ServiceOutputEventArgs e\)  // never called
        \{
           Log\.Debug\(e\.Message\);
        \}

**Comment by cincuranet** [comment]
That's expected. `FbValidation`/sweep does not provide any output (it also does not have `Verbose` property). As long as no exception is thrown, you can assume it did not fail.
