### ISSUE TITLE
Execution of query hangs up/freezes [DNET440]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#436]
Submitted by: @cincuranet

Relate to [DNET304](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET304+in%3Atitle)

//From mailing list\.

The query is:

 update ecc$rejestr set wartosc0=@wartosc, typklucza=@typklucza where
 klucz=@klucz and induzytkownik=@induzytkownik

 The params are:

 @klucz = PersonLocator\_mainGridControl
 @induzytkownik = 1
 @typklucza = 0
 @wartosc =
 db://\(2813f4c2\-87c7\-4c3d\-8175\-d0e03c88d516\)//PersonLocator\_mainGridControl\.x
 ml

 A DDL of ECC$REJESTR:

 CREATE TABLE ECC$REJESTR
 \(
  KLUCZ STRING50\_FIELD DEFAULT '' NOT NULL,
  INDUZYTKOWNIK BIGINT\_FIELD NOT NULL,
  TYPKLUCZA SHORT\_FIELD DEFAULT 0,
  WARTOSC0 STRING250\_FIELD,
  WARTOSC1 INTEGER\_FIELD,
  WARTOSC2 FLOAT\_FIELD,
  WARTOSC3 MONEY\_FIELD,
  WARTOSC4 TIMESTAMP\_FIELD,
  CONSTRAINT PK\_ECC$REJESTR PRIMARY KEY \(KLUCZ,INDUZYTKOWNIK\)
 \);

 ALTER TABLE ECC$REJESTR ADD
  FOREIGN KEY \(INDUZYTKOWNIK\) REFERENCES ECC$UZYTKOWNICY \(ID\);

===

A program simply hangs up/freezes and I have to break debugging\. Then I get this call stack:

                \[Managed to Native Transition\]               

                System\.dll\!System\.Net\.Sockets\.Socket\.Receive\(byte\[\] buffer = \{byte\[4096\]\}, int offset = 0, int size, System\.Net\.Sockets\.SocketFlags socketFlags = None, out System\.Net\.Sockets\.SocketError errorCode = Success\) \+ 0xc4 bytes    

                System\.dll\!System\.Net\.Sockets\.Socket\.Receive\(byte\[\] buffer, int offset, int size, System\.Net\.Sockets\.SocketFlags socketFlags\) \+ 0x20 bytes           

                System\.dll\!System\.Net\.Sockets\.NetworkStream\.Read\(byte\[\] buffer, int offset, int size\) \+ 0x84 bytes 

                mscorlib\.dll\!System\.IO\.BufferedStream\.Read\(byte\[\] array = \{byte\[8\]\}, int offset = 0, int count = 4\) \+ 0xc4 bytes                

                FirebirdSql\.Data\.FirebirdClient\.dll\!FirebirdSql\.Data\.Client\.Managed\.Version10\.XdrStream\.Read\(byte\[\] buffer, int offset, int count\) \+ 0x2e bytes  

                FirebirdSql\.Data\.FirebirdClient\.dll\!FirebirdSql\.Data\.Client\.Managed\.Version10\.XdrStream\.ReadNextOperation\(\) \+ 0x17 bytes          

                FirebirdSql\.Data\.FirebirdClient\.dll\!FirebirdSql\.Data\.Client\.Managed\.Version10\.XdrStream\.ReadOperation\(\) \+ 0x16 bytes    

                FirebirdSql\.Data\.FirebirdClient\.dll\!FirebirdSql\.Data\.Client\.Managed\.Version11\.GdsDatabase\.ReadOperation\(\) \+ 0x19 bytes          

                FirebirdSql\.Data\.FirebirdClient\.dll\!FirebirdSql\.Data\.Client\.Managed\.Version10\.GdsDatabase\.ReadSingleResponse\(\) \+ 0x11 bytes      

                FirebirdSql\.Data\.FirebirdClient\.dll\!FirebirdSql\.Data\.Client\.Managed\.Version10\.GdsDatabase\.ReadResponse\(\) \+ 0x11 bytes    

                 FirebirdSql\.Data\.FirebirdClient\.dll\!FirebirdSql\.Data\.Client\.Managed\.Version10\.GdsDatabase\.ReadGenericResponse\(\) \+ 0xc bytes         

                FirebirdSql\.Data\.FirebirdClient\.dll\!FirebirdSql\.Data\.Client\.Managed\.Version11\.GdsStatement\.Execute\(\) \+ 0x11d bytes    

                 FirebirdSql\.Data\.FirebirdClient\.dll\!FirebirdSql\.Data\.FirebirdClient\.FbCommand\.ExecuteCommand\(System\.Data\.CommandBehavior behavior, bool returnsSet\) \+ 0xc7 bytes              

                FirebirdSql\.Data\.FirebirdClient\.dll\!FirebirdSql\.Data\.FirebirdClient\.FbCommand\.ExecuteNonQuery\(\) \+ 0x40 bytes

**Comment by hhfiddelke** [comment]
I currently can reproduce this error with the Net provider under Open Suse 15.5. The Connection is running over a 50MBit VPN. One problem could be the MTU- Size of the Ethernet Frame it seems that packet fragmenting could be a problem. Reducing the MTU-Size of the client to the MTU-Size of the VPN seems to fix the hang.

Another issue i had, (probably also MTU) was a table with many fields (485) calling the Reader hang for several minutes (Command Timeout=20) (Flamerobin on the same machine worked (but slow) to browse the two records)

**Comment by cincuranet** [comment]
Do you have repro case?

**Comment by hhfiddelke** [comment]
Unfortunately, these MTU- problems aren't easy to repro. In my case i had two computers (OpenSuse 15.5 and SuSe SLES15) both with MTU 1500 and two routers, one with MTU 1500 and the other with MTU 1400 on the internal network side. 
Perhaps it is easier to test if you test it with a client with MTU 1500 and server with MTU 1400 for the write case and the opposite way for the read case. 
In the read case i have a large record the is returned to the client in the write case i am inserting a record with a larger JSON into a BLOB. Both should achieve that more than one network- packet is needed to transfer. 
After changing the MTU on the client- side to 1400, the database- write worked. 
The result is (nearly) the same after several minutes (not FB- Timeouts), an exception with ("Could not read data from connection" or "Could not write data to connection, Could not read data from connection")

**Comment by cincuranet** [comment]
Sorry, unless I have a somewhat reliable repro, there's not much I can do.

**Comment by hhfiddelke** [comment]
I unfortunately have to agree 😢
