### ISSUE TITLE
DDEX Has Problems Adding *Some* TableAdapters to My Typed DataSet [DNET442]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#438]
Submitted by: @cincuranet

Attachments:
[DOMAINS_CREATE.sql](https://github.com/FirebirdSQL/jira-attachments/raw/main/DNET/DNET-442/12168_DOMAINS_CREATE.sql)
[OPENINGTableCreate.sql](https://github.com/FirebirdSQL/jira-attachments/raw/main/DNET/DNET-442/12169_OPENINGTableCreate.sql)
[PROJECTTableCreate.sql](https://github.com/FirebirdSQL/jira-attachments/raw/main/DNET/DNET-442/12170_PROJECTTableCreate.sql)

//From mailing list\.

Steps are as follows:
1\. Create empty database with following parameters:
   \-Path: C:\\Temp\\TestDB\.FDB
    \-UserName: SYSDBA // Password: masterkey
   \-Page Size: 8192
   \-CharSet: ASCII
   \-SQL Dialect: 3
   \-Single File Database

2\. Run the DOMAIN create script, followed by the PROJECT create script, followed by the OPENING create Script

3\. Add the Database to Visual Studio's \(2010\) Server Explorer using the DDEX \.NET Provider

4\. Add a DataSet to a project

5\. Add PROJECT table to the DataSet \(drag and drop\)\. \-\- This will work fine

6\. Add OPENING table to the DataSet \(drag and drop\)\. \-\- This will throw the error: "Failed to merge object\(s\)\. Object reference not set to an instance of an object\."

Note that the order in which you add the tables does not matter, it throws the error either way\.

**Comment by cincuranet** [comment]
Closing because #1001.
