### ISSUE TITLE
SqlFunctions  [DNET526]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#506]
Submitted by: Rand Random (rand.random)

Votes: 1

Hi\.

Pls have a look at the following url:
<https://entityframework.codeplex.com/workitem/1774>

Is there such an implementation in Firebird \.Net Provider?

**Comment by cincuranet** [comment]
EF6 provider here is in maintenance/legacy mode here (see https://groups.google.com/g/firebird-net-provider/c/_0Hwoh5XG_I). If somebody feels like tackling this with good PR, it will be reopened.
