### ISSUE TITLE
EF6's FunctionReturnTableColumns and FunctionFunctionReturnTableColumns set not handled [DNET542]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#519]
Submitted by: @cincuranet

Is related to [DNET454](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET454+in%3Atitle)
Is duplicated by [DNET557](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET557+in%3Atitle)

Votes: 1

An error occurred while connecting to the database\. The database might be unavailable\. An exception of type 'System\.Data\.Entity\.Core\.EntityCommandCompilationException' occurred\. The error message is: 'An error occurred while preparing the command definition\. See the inner exception for details\.
The inner exception caught was of type 'System\.Data\.Entity\.Core\.MappingException', with this error message: '
StoreSchemaMappingVersion3\(3,4\) : error 3027: No mapping specified for the following EntitySet/AssociationSet \- FunctionReturnTableColumns, FunctionFunctionReturnTableColumns\.'\.'\.

**Comment by DanCypress** [comment]
I am using 4.2.0.0 and I am facing this [problem](https://www.bostonmahoodcleaning.com).
