### ISSUE TITLE
Firebird .Net Provider Installer doesn't remove entries from the machine.config <DbProviderFactories> when removing/repair the provider [DNET560]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#533]
Submitted by: André Ziegler (andre.ziegler)

Votes: 3

The Installer has some issues with the machine\.config file\. When you remove and older provider, the config settings for Firebird under <DbProviderFactories\> are still left in the config\. 

Wen you now install a new FB provider version, a 2nd entry is added\. This caused VS crashes for me when working with DDEX provider when trying to do Reverse Engineering a DB to EDMX Model\. Also, when you repair the provider, a second entry is added\. Also the structure of the XML config is corrupted, when the other entry is added and this causes that other providers like SQL CE fail to load\.

Removing all the bad entries fixes both VS issues \(crash and SQL CE errors\)\.

**Comment by cincuranet** [comment]
Duplicate of #968.
