### ISSUE TITLE
Support for Firebird 3.0 [DNET630]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#590]
Submitted by: Mark Junker (fubar-coder)

Jira\_subtask\_outward [DNET631](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET631+in%3Atitle)
Jira\_subtask\_outward [DNET642](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET642+in%3Atitle)
Jira\_subtask\_outward [DNET644](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET644+in%3Atitle)
Jira\_subtask\_outward [DNET645](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET645+in%3Atitle)
Jira\_subtask\_outward [DNET647](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET647+in%3Atitle)
Jira\_subtask\_outward [DNET649](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET649+in%3Atitle)
Jira\_subtask\_outward [DNET650](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET650+in%3Atitle)
Jira\_subtask\_outward [DNET652](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET652+in%3Atitle)
Jira\_subtask\_outward [DNET653](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET653+in%3Atitle)
Jira\_subtask\_outward [DNET672](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET672+in%3Atitle)
Jira\_subtask\_outward [DNET675](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET675+in%3Atitle)
Jira\_subtask\_outward [DNET676](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET676+in%3Atitle)
Jira\_subtask\_outward [DNET706](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET706+in%3Atitle)
Jira\_subtask\_outward [DNET760](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET760+in%3Atitle)
Jira\_subtask\_outward [DNET773](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET773+in%3Atitle)
Jira\_subtask\_outward [DNET784](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET784+in%3Atitle)
Relate to [DNET836](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET836+in%3Atitle)

Votes: 4

It seems that the Firebird <http://ADO.NET> driver doesn't support Firebird 3\.0 beta 2 yet\. At least two things come to mind that probably have to be changed:

\* Support for BOOLEAN data type
\* Support for changed data structures
  \* I found at least one situation where the data structure was changed: When I try to open an already opened embedded database

**Comment by cincuranet** [comment]
EF6 provider here is in maintenance/legacy mode here (see https://groups.google.com/g/firebird-net-provider/c/_0Hwoh5XG_I). If somebody feels like tackling this with good PR, it will be reopened.

**Comment by cincuranet** [comment]
Closing in favor of separate issues.

**Comment by dyemanov** [comment]
AFAIS, the issue I described earlier still exists. It makes monitoring usage impossible for many clients using .NET provider. Jiri, could you please post an update, when we may expect it to be fixed/improved?

**Comment by cincuranet** [comment]
@dyemanov Can you create separate issue for that?

**Comment by dyemanov** [comment]
Done, see #1020.

**Comment by cincuranet** [comment]
Thanks.
