### ISSUE TITLE
COUNT returning Int64 (EF) [DNET644]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#602]
Submitted by: @cincuranet

Jira\_subtask\_inward [DNET630](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET630+in%3Atitle)

**Comment by cincuranet** [comment]
EF6 provider here is in maintenance/legacy mode here (see https://groups.google.com/g/firebird-net-provider/c/_0Hwoh5XG_I). If somebody feels like tackling this with good PR, it will be reopened.
