### ISSUE TITLE
NOT NULL alteration support in EF Migrations [DNET685]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#638]
Submitted by: @cincuranet

Relate to [DNET661](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET661+in%3Atitle)

**Comment by cincuranet** [comment]
EF6 provider here is in maintenance/legacy mode here (see https://groups.google.com/g/firebird-net-provider/c/_0Hwoh5XG_I). If somebody feels like tackling this with good PR, it will be reopened.
