### ISSUE TITLE
Migration Sql generate for AddColumn operation for non nullable Guid field is wrong [DNET700]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#651]
Submitted by: Fabiano Rezende (fabiano.rezende)

The Migration below

public partial class MyMigration : DbMigration
\{
	public override void Up\(\)
	\{
		AddColumn\("dbo\.TableName", "Id", c =\> c\.Guid\(nullable: false\)\);
	\}
\}

Generats the Sql:
ALTER TABLE "TableName" ADD "Id" CHAR\(16\) CHARACTER SET OCTETS DEFAULT CHAR\_TO\_UUID\('00000000\-0000\-0000\-0000\-000000000000'\) NOT NULL

Firebird does not recognize DEFAULT CHAR\_TO\_UUID\('00000000\-0000\-0000\-0000\-000000000000'\)

**Comment by cincuranet** [comment]
EF6 provider here is in maintenance/legacy mode here (see https://groups.google.com/g/firebird-net-provider/c/_0Hwoh5XG_I). If somebody feels like tackling this with good PR, it will be reopened.
