### ISSUE TITLE
Update the referenced Microsoft.BCL packages to latest version for NET40 projects [DNET762]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#704]
Submitted by: André Ziegler (andre.ziegler)

Is replaced by [DNET774](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET774+in%3Atitle)

Please update the referenced Microsoft\.BCL packages to latest version for NET40 projects because I use newer versions and here I get conflict\. 

You use

  <package id="Microsoft\.Bcl" version="1\.1\.8" targetFramework="net40\-client" /\>
  <package id="Microsoft\.Bcl\.Async" version="1\.0\.168" targetFramework="net40\-client" /\>
  <package id="Microsoft\.Bcl\.Build" version="1\.0\.14" targetFramework="net40\-client" /\>

but there are 2 updates:

  <package id="Microsoft\.Bcl" version="1\.1\.10" 
  <package id="Microsoft\.Bcl\.Build" version="1\.0\.21" 

I have no idea why you added old versions when there are already newer ones available for years\.

I've added assemblyBinding entriy in app\.config to redirect the referenced System\.Runtime to the newer 2\.6\.10\.0\. \(Microsoft\.Bcl" version="1\.1\.10" \) but when I capture a trace with WPR\.exe and analyze the ETL I still see "System\.IO\.FileLoadException" entry when \.net tries to load System\.Runtime in version  2\.6\.8\.0\.

Commits: FirebirdSQL/NETProvider@668fd78a39dcfd80081e556534160ae06be356a4

**Comment by DanCypress** [comment]
Yes, you can force version on your own in [NuGet package file](https://parsamohebi.com/beverly-hills).
