### ISSUE TITLE
Mapping numeric types in the same configurable way you can do in Oracle [DNET796]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#733]
Submitted by: Roberto Carlos da Silva (robertosistemas)

It would be great if in the Firebird \.NET Drive there was a way to map the same numeric types you can do in the Oracle Driver\.
It would solve various system and framework migration incompatibility issues and make it easier to choose firebird as a database for the \.NET platform\. I think it would be very easy to do that\.

<https://docs.oracle.com/database/121/ODPNT/entityDataTypeMapping.htm#ODPNT8300>

**Comment by cincuranet** [comment]
In EF Core this could be done via value converters now.

EF6 provider is in maintenance/legacy mode.
