### ISSUE TITLE
Support for Firebird 4.0 [DNET812]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#747]
Submitted by: @cincuranet

Jira\_subtask\_outward [DNET925](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET925+in%3Atitle)
Jira\_subtask\_outward [DNET924](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET924+in%3Atitle)
Jira\_subtask\_outward [DNET923](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET923+in%3Atitle)
Jira\_subtask\_outward [DNET922](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET922+in%3Atitle)
Jira\_subtask\_outward [DNET921](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET921+in%3Atitle)
Jira\_subtask\_outward [DNET907](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET907+in%3Atitle)
Jira\_subtask\_outward [DNET943](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET943+in%3Atitle)
Jira\_subtask\_outward [DNET942](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET942+in%3Atitle)
Jira\_subtask\_outward [DNET950](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET950+in%3Atitle)
Jira\_subtask\_outward [DNET951](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET951+in%3Atitle)
Jira\_subtask\_outward [DNET952](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET952+in%3Atitle)
Jira\_subtask\_outward [DNET953](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET953+in%3Atitle)
Jira\_subtask\_outward [DNET954](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET954+in%3Atitle)
Jira\_subtask\_outward [DNET955](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET955+in%3Atitle)
Jira\_subtask\_outward [DNET956](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET956+in%3Atitle)
Jira\_subtask\_outward [DNET957](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET957+in%3Atitle)
Jira\_subtask\_outward [DNET958](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET958+in%3Atitle)
Jira\_subtask\_outward [DNET959](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET959+in%3Atitle)
Jira\_subtask\_outward [DNET960](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET960+in%3Atitle)
Jira\_subtask\_outward [DNET961](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET961+in%3Atitle)
Jira\_subtask\_outward [DNET962](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET962+in%3Atitle)
Jira\_subtask\_outward [DNET963](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET963+in%3Atitle)
Jira\_subtask\_outward [DNET964](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET964+in%3Atitle)
Jira\_subtask\_outward [DNET965](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET965+in%3Atitle)
Jira\_subtask\_outward [DNET966](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET966+in%3Atitle)
Jira\_subtask\_outward [DNET990](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET990+in%3Atitle)
Jira\_subtask\_outward [DNET1020](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET1020+in%3Atitle)
Jira\_subtask\_outward [DNET1021](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET1021+in%3Atitle)
Jira\_subtask\_outward [DNET1022](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET1022+in%3Atitle)
Jira\_subtask\_outward [DNET1023](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET1023+in%3Atitle)
Jira\_subtask\_outward [DNET1024](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET1024+in%3Atitle)
Jira\_subtask\_outward [DNET1025](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET1025+in%3Atitle)
Jira\_subtask\_outward [DNET1026](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET1026+in%3Atitle)
Jira\_subtask\_outward [DNET1027](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET1027+in%3Atitle)
Jira\_subtask\_outward [DNET1028](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET1028+in%3Atitle)
Jira\_subtask\_outward [DNET1029](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET1029+in%3Atitle)

**Comment by cincuranet** [comment]
Closing in favor of separate issues.
