### ISSUE TITLE
FB3 bool support in EF [DNET836]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#771]
Submitted by: @cincuranet

Is related to [DNET630](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET630+in%3Atitle)
Is related to [DNET631](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET631+in%3Atitle)

**Comment by cincuranet** [comment]
EF6 provider here is in maintenance/legacy mode here (see https://groups.google.com/g/firebird-net-provider/c/_0Hwoh5XG_I). If somebody feels like tackling this with good PR, it will be reopened.
