### ISSUE TITLE
Failing to connect to Firebird from EF Core 3 [DNET902]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#829]
Submitted by: John Greco (jfgreco)

Trying to utilize:  services\.AddDbContext<SheaDbContext\>\(options =\> options\.UseFirebird\(connectionString\)\);

Raises an exception: 

"Method 'get\_Info' in type 'FirebirdSql\.EntityFrameworkCore\.Firebird\.Infrastructure\.Internal\.FbOptionsExtension' from assembly 'FirebirdSql\.EntityFrameworkCore\.Firebird, Version=7\.1\.1\.0, Culture=neutral, PublicKeyToken=7a73ef09980c56c9' does not have an implementation\."	string

**Comment by janhenk** [comment]
I'm having this same issue with:
'Method 'get_Info' in type 'EntityFrameworkCore.FirebirdSql.Infrastructure.Internal.FbOptionsExtension' from assembly 'EntityFrameworkCore.FirebirdSql, Version=2.1.2.2, Culture=neutral, PublicKeyToken=590af85568ed71f5' does not have an implementation.'
tested on all versions
EntityFrameworkCore.FirebirdSql 2.0.1 => 2.1.2.2  

Application .Net 5.0 Console Application

**Comment by cincuranet** [comment]
Assembly _EntityFrameworkCore.FirebirdSql_ is not this provider.
