### ISSUE TITLE
Unable to complete network request to host "{0}". error , but no args [DNET904]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#831]
Submitted by: EzberYazan (febitbilisim)

ERR: 335544721 : Unable to complete network request to host "\{0\}"\.

but no arg on : private static void AppendMessage\(StringBuilder builder, string message, List<string\> args\) \{
i solved pratically adding 3 arg for general purposes;

if \(args == null \|\| args\.Count == 0\) \{ args\.Add\("no\-arg\-defined"\); args\.Add\("no\-arg\-defined"\); args\.Add\("no\-arg\-defined"\); \}

  private static void AppendMessage\(StringBuilder builder, string message, List<string\> args\) \{
				if \(builder\.Length \> 0\) \{
					 builder\.Append\(Environment\.NewLine\);
				\}
				if \(args == null \|\| args\.Count == 0\) \{ args\.Add\("no\-arg\-defined"\); args\.Add\("no\-arg\-defined"\); args\.Add\("no\-arg\-defined"\); \}
				builder\.AppendFormat\(CultureInfo\.CurrentCulture, message, args\.ToArray\(\)\);
		  \}

**Comment by cincuranet** [comment]
Looking at all the lines with `isc_network_error` in the code, at the moment all contain proper data source argument. I probably cleaned it up during some refactoring.
