### ISSUE TITLE
FbCommand.ExecuteNonQuery return value [DNET927]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#852]
Submitted by: @cincuranet

The FbCommand\.ExecuteNonQuery should return \-1 for everything except insert, update, delete, according to "spec"\.

<https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbcommand.executenonquery>

"For UPDATE, INSERT, and DELETE statements, the return value is the number of rows affected by the command\. For all other types of statements, the return value is \-1\."

Commits: FirebirdSQL/NETProvider@da206eb89163d0f515444aed178aab4479ba182f

**Comment by cincuranet** [comment]
@viegasfh The "problem" is, that `INSERT ... RETURNING` Firebird reports as "stored procedure" command type.

**Comment by viegasfh** [comment]
OK, thanks! I have added the  condition to test it against -1.
