### ISSUE TITLE
Cast of string values to VARCHAR(8191) results in "Implementation limit exceeded" [DNET934]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#857]
Submitted by: Daniel Richter (drichter)

Is duplicated by [DNET980](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET980+in%3Atitle)

For string values in queries, the generated SQL results in CASTs to VARCHAR\(8191\)
   dataContext\.Articles\.Select\(\_ =\> new \{ A1 = "1A", A2 = "2A" \}\)
generates SQL such as
   SELECT CAST\(\_UTF8'1A' AS VARCHAR\(8191\)\) AS "A1", CAST\(\_UTF8'2A' AS VARCHAR\(8191\)\) AS "A2" FROM "ARTICLE"
   
In case the string value is used in multiple\* columns, the SQL command execution results in an error "SQL error code = \-204, Implementation limit exceeded, block size exceeds implementation restriction"\.

\*\) With charset UTF8 the query fails with 2\+ columns using string values\. The amount of string values used in the column does not seem to affect the outcome \(50\+ string values in one column still work\)\.
   With charset WIN1252 the query fails with 8\+ columns using one string value\. Using multiple string values in a column shows different results; in some cases, 8\+ string values used in the entire query fails, in some cases not\.

It does not matter whether the string value is used inline or as a captured variable \(the cast is also inserted for those\)\.

Because of the following code in SqlGenerator\.cs, Visit\(DbConstantExpression\)
   // constant is always considered Unicode
   isUnicode = true;
   var length = MetadataHelpers\.GetFacetValueOrDefault<int?\>\(e\.ResultType,MetadataHelpers\.MaxLengthFacetName,null\)
	   ?? \(isUnicode ? FbProviderManifest\.UnicodeVarcharMaxSize : FbProviderManifest\.AsciiVarcharMaxSize\);
The length will result in FbProviderManifest\.UnicodeVarcharMaxSize \(8191\)\.

Is the CAST to VARCHAR\(n\) really necessary? The following two solutions will work without problems \(so far\) for my use\-case:

1\) Don't pass the explicitLength parameter to FormatString \(SqlGenerator\.cs\), so the length of the string value will be used:
   SELECT CAST\(\_UTF8'ABC' AS VARCHAR\(3\)\) AS "A1", CAST\(\_UTF8'DEFGH' AS VARCHAR\(5\)\) AS "A2" FROM "ARTICLE"
   
2\) Omit the CAST entirely\.
   SELECT \_UTF8'ABC' AS "A1", \_UTF8'DEFGH' AS "A2" FROM "ARTICLE"

**Comment by cincuranet** [comment]
EF6 provider here is in maintenance/legacy mode here (see https://groups.google.com/g/firebird-net-provider/c/_0Hwoh5XG_I). If somebody feels like tackling this with good PR, it will be reopened.
