### ISSUE TITLE
Support for Srp256 [DNET942]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#864]
Submitted by: @cincuranet

Jira\_subtask\_inward [DNET812](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET812+in%3Atitle)
Is duplicated by [DNET973](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET973+in%3Atitle)

Votes: 1

**Comment by mrotteveel** [comment]
For reference, this was the initial change in Jaybird to add Srp224, Srp256, Srp384 and Srp512 support: https://github.com/FirebirdSQL/jaybird/commit/a61214bf

**Comment by cincuranet** [comment]
The SRP algorithm part is now part of branch [srp256](https://github.com/FirebirdSQL/NETProvider/tree/srp256). The merge happens after #967.

**Comment by cincuranet** [comment]
Done in bf2feedf0b9c3042722887339ac7e011b5031944.
