### ISSUE TITLE
Update ReservedWords in FbMetaData.xml [DNET949]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#869]
Submitted by: @cincuranet

**Comment by cincuranet** [comment]
@mrotteveel Thanks, that would help. And would be faster than trying to fishing the words out from `parse.y`, etc.

**Comment by mrotteveel** [comment]
[fb_reservedwords_2022-05-08.zip](https://github.com/FirebirdSQL/NETProvider/files/9267860/fb_reservedwords_2022-05-08.zip)

This is a Firebird 3.0 backup.

It has three tables:

- `DBVERSION`, used by the [firebird-reserved-words](https://github.com/mrotteveel/firebird-reserved-words) tool I use to manage this database, you can ignore this
- `FB_KEYWORD`, Firebird keywords per version, with columns:
  -  `WORD`, the keyword
  - `FB_VERSION`, the version (major.minor only, even for keywords introduced in a maintenance-release), the db only has keywords for 2.0, 2.1, 2.5, 3.0 and 4.0
  - `RESERVED`, indicates if the keyword is a reserved word
- `SQL_KEYWORD`, SQL standard keywords per SQL standard version, with columns:
  - `WORD`, the keyword
  - `SQL_VERSION`, SQL version (4-digit year), the db only has 1992, 2003 (based on a pre-release of the standard), 2016 (based on the official release)
  - `RESERVED`, indicates if the keyword is a reserved word

The current version is based on:
- 2.5: 2.5.9
- 3.0: 3.0.4 (IIRC, might be a later release)
- 4.0: 4.0.1

The keywords do not include the operators, parentheses and comma (see https://github.com/mrotteveel/firebird-reserved-words/blob/master/keywords/firebird/fb_general_keywords_to_remove.txt).

**Comment by mrotteveel** [comment]
(obviously, that filename should have been fb_reservedwords_2022-08-05.zip, but apparently my brain was absent while typing that filename)

**Comment by cincuranet** [comment]
Thanks Mark.
