### ISSUE TITLE
Support for isc_tpb_at_snapshot_number <snapshot number length> <snapshotnumber> [DNET951]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#871]
Submitted by: @cincuranet

Jira\_subtask\_inward [DNET812](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET812+in%3Atitle)

**Comment by cincuranet** [comment]
Relates to #836.

**Comment by cincuranet** [comment]
Done via 54702aa6.
