### ISSUE TITLE
Support for statement timeout [DNET957]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#877]
Submitted by: @cincuranet

Jira\_subtask\_inward [DNET812](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET812+in%3Atitle)

- [x] Support on `FbCommand`
- [x] Support on `isc_database_info`

**Comment by cincuranet** [comment]
Done via 8f7e8e2c1adac41308b2199a37c4e21aaa0e8819 and 730827ca633fb91cc644b041044a023e8612d8fa.
