### ISSUE TITLE
Any and AnyAsync Dynamic SQL Error [DNET979]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#897]
Submitted by: Benjamyn Williams (ben_williams)

When using Any and AnyAsync against a DbSet it results in:

Dynamic SQL Error
SQL error code = \-104
Token unknown \- line 1, column 8
EXISTS

Generated query:

SELECT EXISTS \(
    SELECT 1
    FROM "TEST\_TABLE" AS "t"\) FROM RDB$DATABASE

**Comment by cincuranet** [comment]
EF6 provider here is in maintenance/legacy mode here (see https://groups.google.com/g/firebird-net-provider/c/_0Hwoh5XG_I). If somebody feels like tackling this with good PR, it will be reopened.
