### ISSUE TITLE
Validate leading zeros handling in Srp SHA [DNET986]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#904]
Submitted by: @cincuranet

Is related to [JDBC635](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC635+in%3Atitle)

As reported in [JDBC635](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC635+in%3Atitle)\.

**Comment by cincuranet** [comment]
11fe85c4a9c25f483a48f7efef2b34ce002a8c76
