### ISSUE TITLE
Functions (SQL functions) in FbSchema [DNET992]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#909]
Submitted by: @cincuranet

Is related to [DNET983](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET983+in%3Atitle)

**Comment by cincuranet** [comment]
I think I was little too terse with the description. :) What I see missing is function arguments and function privileges. Functions (both UDF, UDR and SQL) are there, as far as I can tell.

Did I miss something @FransBouma, @gonline?

**Comment by FransBouma** [comment]
I only support the reverse engineering of stored procs on firebird so looks good to me :)
