### ISSUE TITLE
Unhandled exception at FirebirdSql.Data.Client.Managed.FirebirdNetworkStream.Flush() [DNET1014]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#927]
Submitted by: @luronumen

ACTUAL RESULT:
Under certain conditions where network failures can happen more frequently \(high latency network\), the following unhandled exception can happen: 

See the end of this message for details on invoking 
just\-in\-time \(JIT\) debugging instead of this dialog box\.

\*\*\*\*\*\*\*\*\*\*\*\*\*\* Exception Text \*\*\*\*\*\*\*\*\*\*\*\*\*\*
FirebirdSql\.Data\.Common\.IscException: Unable to complete network request to host "
No message for error code 335544721 found\. \-\-\-\> System\.IO\.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host\. \-\-\-\> System\.Net\.Sockets\.SocketException: An existing connection was forcibly closed by the remote host
   at System\.Net\.Sockets\.Socket\.Send\(Byte\[\] buffer, Int32 offset, Int32 size, SocketFlags socketFlags\)
   at System\.Net\.Sockets\.NetworkStream\.Write\(Byte\[\] buffer, Int32 offset, Int32 size\)
   \-\-\- End of inner exception stack trace \-\-\-
   at System\.Net\.Sockets\.NetworkStream\.Write\(Byte\[\] buffer, Int32 offset, Int32 size\)
   at FirebirdSql\.Data\.Client\.Managed\.FirebirdNetworkStream\.Flush\(\)
   at FirebirdSql\.Data\.Client\.Managed\.Version10\.GdsStatement\.DoFreePacket\(Int32 option\)
   \-\-\- End of inner exception stack trace \-\-\-
   at FirebirdSql\.Data\.Client\.Managed\.Version10\.GdsStatement\.DoFreePacket\(Int32 option\)
   at FirebirdSql\.Data\.Client\.Managed\.Version11\.GdsStatement\.Free\(Int32 option\)
   at FirebirdSql\.Data\.Common\.StatementBase\.Release\(\)
   at FirebirdSql\.Data\.Client\.Managed\.Version10\.GdsStatement\.Dispose\(\)
   at FirebirdSql\.Data\.FirebirdClient\.FbCommand\.Release\(\)
   at FirebirdSql\.Data\.FirebirdClient\.FbCommand\.Dispose\(Boolean disposing\)
   at System\.ComponentModel\.Component\.Dispose\(\)
   at CHRONOS\.Models\.Databases\.FirebirdSQLDatabase\.SelectProcedure\(String procedureName, String\[\] inputParameters, DataTable dataTable, Boolean poolingStatus\)

EXPECTED RESULT
This unhandled exception should be redirected to the FbException class\.

OHTER INFORMATION
Here is the code of the procedure that the unhandled exception happens:
        private static bool SelectProcedure\(string procedureName, string\[\] inputParameters, out DataTable dataTable, bool poolingStatus = true\)
        \{
            dataTable = new DataTable\(\);
            using \(var fbConnection = new FbConnection\(ConnectionString\(\)\)\)
            using \(var fbCommand = new FbCommand\(procedureName, fbConnection\)\)
                try
                \{
                    Cursor\.Current = Cursors\.WaitCursor;
                    fbCommand\.CommandType = CommandType\.StoredProcedure;
                    //INPUT PARAMETERS
                    for \(var i = 0; i < inputParameters\.Length; i\+\+\)
                        fbCommand\.Parameters\.Add\("@" \+ i, inputParameters\[i\]\)\.Direction = ParameterDirection\.Input;
                    //OPEN CONNECTION
                    fbConnection\.Open\(\);
                    //SELECT PROCEDURE
                    using \(var fbDataReader = fbCommand\.ExecuteReader\(\)\)
                        dataTable\.Load\(fbDataReader\);
                    NotifyReconnection\(\);
                    Utility\.Log\("SP", procedureName\);
                    return true;
                \}
                catch \(FbException ex\)
                \{
                    if \(poolingStatus\)
                        return SelectProcedure\(procedureName, inputParameters, out dataTable, false\);
                    else NotifyException\(ex\);
                    return false;
                \}
                finally
                \{
                    Cursor\.Current = Cursors\.Default;
                \}
        \}

**Comment by cincuranet** [comment]
@luronumen Would you mind trying [this build](https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/actions/runs/1026579657) to see everything behaves as expected?

**Comment by luronumen** [comment]
> @luronumen Would you mind trying [this build](https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/actions/runs/1026579657) to see everything behaves as expected?

Hi @cincuranet 

How can I download _FirebirdSql.Data.FirebirdClient.dll_ from this site?
Could you generate an alpha version and publish it to https://www.nuget.org/packages/FirebirdSql.Data.FirebirdClient/ ?

First of all thank you very much for working to fix this issue!

**Comment by cincuranet** [comment]
Both NuGet and the dll are in [this](https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/suites/3226533751/artifacts/74757953).

**Comment by luronumen** [comment]
> Both NuGet and the dll are in [this](https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/suites/3226533751/artifacts/74757953).

Hi @cincuranet 

The issue is still reproducible on this version. See: [ERROR.txt](https://github.com/FirebirdSQL/NETProvider/files/6815655/ERROR.txt)

**Comment by cincuranet** [comment]
That looks correct. Now the exception is `FbException` and should be handled accordingly (around `FbCommand.Dispose`).

**Comment by luronumen** [comment]
> That looks correct. Now the exception is `FbException` and should be handled accordingly (around `FbCommand.Dispose`).

Hi @cincuranet 

You mean this error has to be handled in my code?
Here is my code where the exception happens: [SelectProcedure.txt](https://github.com/FirebirdSQL/NETProvider/files/6815742/SelectProcedure.txt)

Do you know how I can improve it to catch this exception?

Thanks in advance,
Luciano

**Comment by cincuranet** [comment]
Yes. You need the try-catch block around the `fbCommand` using block.

**Comment by luronumen** [comment]
Hi @cincuranet 

You means like that: [SelectProcedureNewVersion.txt](https://github.com/FirebirdSQL/NETProvider/files/6815865/SelectProcedureNewVersion.txt)

**Comment by cincuranet** [comment]
Yes, that's one way to do it.

**Comment by cincuranet** [comment]
Done in 836ba7a8.

**Comment by luronumen** [comment]
Hi @cincuranet 

I retested this issue using this [build](https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/suites/3226533751/artifacts/74757953) version and this [SelectProcedureNewVersion.txt](https://github.com/FirebirdSQL/NETProvider/files/6815865/SelectProcedureNewVersion.txt) version and the issue is no longer reproducible!

Thank you very much for the fix!

Best Regards,
Luciano
