### ISSUE TITLE
Handle script generation by using SET TERM [DNET1017]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#930]
Submitted by: @cincuranet

Now possible in EF Core 5: <https://github.com/dotnet/efcore/issues/14746>\.

**Comment by cincuranet** [comment]
Solved via 36eeedf6.

**Comment by cincuranet** [comment]
Breaking change because of incompatible, although trivial, change in `IFbMigrationSqlGeneratorBehavior`.
