### ISSUE TITLE
Support for fb_info_protocol_version [DNET1020]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#933]
Submitted by: @cincuranet

Jira\_subtask\_inward [DNET812](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET812+in%3Atitle)

**Comment by cincuranet** [comment]
This is not yet implemented in FB4.

**Comment by cincuranet** [comment]
https://github.com/FirebirdSQL/firebird/issues/6954
