### ISSUE TITLE
Support for fb_info_creation_timestamp_tz [DNET1023]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#936]
Submitted by: @cincuranet

Jira\_subtask\_inward [DNET812](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET812+in%3Atitle)

**Comment by cincuranet** [comment]
Waiting for https://github.com/FirebirdSQL/firebird/issues/6955 for completion and testing.
