### ISSUE TITLE
Async operations executed with cancelled CancellationToken [DNET1043]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#954]
Submitted by: mace windu (mace_windu)

After update to recent provider version \(8\.0\.1\.0\) which introduce async operations support, several of our tests, that check proper handling of cancelled token started to fail as they expect OperationCanceledException, but instead of it operation succedded \(similar issue we recently reported for npgsql 5 release <https://github.com/npgsql/npgsql/issues/3379>, so you can use sample code from there and replace npgsql types with fb types\)\.

I have no list of all affected async operations, but at least ExecuteNonQueryAsync is not failing as it is expected\.

**Comment by tborgesvieira** [comment]
The problem apparently affected the functioning of Dapper too, after updating commands with QueryAsync are not respecting await
