### ISSUE TITLE
The 8.0.1 MSI doesn't remove the DbProviderFactory of 6.x versions from the x64 machine.config file

### ISSUE THREAD

**Issue by FransBouma** [FirebirdSQL/NETProvider#968]
Hi,

I installed the new firebird sql client v8.0.1 using the msi from github and I tried to grab the DbProviderFactory instance from the DbProviderFactories table but it reported an error that the Firebird client's DbProviderFactory was present multiple times. Checking the machine.config file I saw the DbProviderFactory registration of the v6.x I had installed (and which was uninstalled now), was still present. Removing that manually solved it. 

Not sure if this is an issue with the 8.0.1 MSI where it doesn't remove factory registrations prior to adding its new one, or an issue with the older 6.x MSI *uninstall* code where it forgets to remove its factory registration. If the latter, then this issue might help others running into this issue. If the former, it might be a good idea to clean up DbProviderFactory registrations for Firebird client prior to adding the new registration (although this can be a PITA to get right I recon... )

**Comment by cincuranet** [comment]
Hmm, the [delete action is in the installer script](https://github.com/FirebirdSQL/NETProvider/blob/master/Provider/installer/Installer.wxs#L93). Not sure why it wasn't removed during uninstall.

**Comment by FransBouma** [comment]
Might be the 6.4 version I had installed didn't have the proper line in its uninstall script as it left the line in the machine.config (or it didnt match with the specification for some odd reason). I didn't manually correct the 32bit config file, so it's still present:

```xml
  <system.data>
    <DbProviderFactories>
      <add name="FirebirdClient Data Provider" invariant="FirebirdSql.Data.FirebirdClient" description=".NET Framework Data Provider for Firebird" type="FirebirdSql.Data.FirebirdClient.FirebirdClientFactory, FirebirdSql.Data.FirebirdClient, Version=6.4.0.0, Culture=neutral, PublicKeyToken=3750abcc3150b00c"/>

...

    <add name="FirebirdClient Data Provider" invariant="FirebirdSql.Data.FirebirdClient" description=".NET Framework Data Provider for Firebird" type="FirebirdSql.Data.FirebirdClient.FirebirdClientFactory, FirebirdSql.Data.FirebirdClient, Version=8.0.1.0, Culture=neutral, PublicKeyToken=3750abcc3150b00c"/></DbProviderFactories>
  </system.data>
```

It's highly likely an issue with the old msi of v6.4. I'll now uninstall and reinstall the 8.0.1 to see if it removes it correctly and report back

**Comment by FransBouma** [comment]
Nope, uninstalling firebird client 8.0.1 still leaves the DbProviderFactory line in the machine.config file. As there are less spaces in front of it, it might mismatch there, will manually correct it and retry

**Comment by FransBouma** [comment]
Nope, spacing doesn't have anything to do with it, it simply doesn't remove the line when uninstalling. don't know what it could be tho. Does it remove the line from the machine.config in your setup?

**Comment by cincuranet** [comment]
Tried now on a clean VM and it's not removed. But I have no clue what's wrong. 🤷‍♂️ I'll try some google-fu and we'll see.

**Comment by cincuranet** [comment]
Ha, looks like I found it. Can you check [this](https://www.uschovna.cz/zasilka/NMC24NWHSCAIYT3H-B6L/) build? Looks correct on my side.

**Comment by FransBouma** [comment]
Yep that fixed it! 👍 :)

**Comment by cincuranet** [comment]
Great. The 3a2a7914 fixed it.
