### ISSUE TITLE
EntityFrameworkCore scaffolding does not support Firebird 2.5

### ISSUE THREAD

**Issue by SJFriedl** [FirebirdSQL/NETProvider#975]
On a .net 5 project in Visual Studio 2019, with `FirebirdSql.Data.FirebirdClient` and `FirebirdSql.EntityFrameworkCore.Firebird` modules, both version 8.0.1, running the `Scaffold-dbcontext` command with a connection string pointing to a Firebird 2.5 database yields:
```
FirebirdSql.Data.FirebirdClient.FbException (0x80004005): Dynamic SQL Error
SQL error code = -206
Column unknown
RF.RDB$IDENTITY_TYPE
At line 35, column 28
```
I believe `rdb$IDENTITY_TYPE` was added in Firebird 3.0, and this version awareness is reflected in the schema code in `Schema/FbColumns.cs` where a `MajorVersionNumber` test elides this column, but the same test is not found in `Scaffolding/Internal/FbDatabaseModelFactory.cs`.

I have played around with actually fixing this, but I've never done a github pull request before, so I'll file this as an Issue while I sort out my efforts.

**Comment by cincuranet** [comment]
Yes, that's expected. At least Firebird 3.0 is required for EF Core provider. It's not only about scaffolding, but also query and update pipelines.

**Comment by SJFriedl** [comment]
Well that saves me a lot of time. Is this a permanent thing, with no plans for support, or just a low-priority thing to maybe get around to someday when somebody puts in the work?  Might this be documented somewhere?

**Comment by cincuranet** [comment]
> just a low-priority thing 

Yes. Kind of. The reason is, FB 2.5 is end-of-life since June 2019 and also resources.

> to maybe get around to someday when somebody puts in the work? 

Exactly. When somebody creates a quality PR, I don't have problem merging that right away.

> Might this be documented somewhere?

I thought I did, but as it turns out I didn't. Fixing right now ([page](https://github.com/FirebirdSQL/NETProvider/blob/master/Provider/docs/entity-framework-core.md)).

**Comment by SJFriedl** [comment]
Understood; I've created a pull request - my first, please be gentle - that adds <3.0 support to the scaffolding. Just creating all the `table.cs` files is useful enough (to me) that it seems like like a reasonable incremental step to pre-3.0 support.

**Comment by cincuranet** [comment]
Looks like @SJFriedl is not responding in #976. I'll take it, do the requested changes and merge it. Other than that, I'll not spend more time on it because FB2.5 is out of support. I'll try to do that in next few days.

**Comment by cincuranet** [comment]
Done via faedc6e7.
