### ISSUE TITLE
Problem using entityframework core

### ISSUE THREAD

**Issue by DBernaert2** [FirebirdSQL/NETProvider#977]
Hi,

Using the latest version of entityframe core en the firebird netprovider.
I just started playing with these 2 coming from a Delphi environment.
I changed a field from not required to required in my class and created a new migration.
This gives me the following migration:

namespace TestApp.Migrations
{
    public partial class Set_first_name_required : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "First_name",
                table: "HotelRooms",
                type: "VARCHAR(35)",
                maxLength: 35,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "VARCHAR(35)",
                oldMaxLength: 35,
                oldNullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "First_name",
                table: "HotelRooms",
                type: "VARCHAR(35)",
                maxLength: 35,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "VARCHAR(35)",
                oldMaxLength: 35);
        }
    }
}

When executing the migration (update-database), i get the following error:
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (20ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER TABLE "HotelRooms" ALTER COLUMN "First_name" TYPE VARCHAR(35) NOT NULL;
Failed executing DbCommand (20ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE "HotelRooms" ALTER COLUMN "First_name" TYPE VARCHAR(35) NOT NULL;
FirebirdSql.Data.FirebirdClient.FbException (0x80004005): Dynamic SQL Error
SQL error code = -104
Token unknown - line 1, column 69

What am i doing wrong? I'm new, sorry.

Thank you,
Bernaert Dominique

**Comment by cincuranet** [comment]
Yeah, the statement generated is wrong. Fixed in d000fd9.

**Comment by Rand-Random** [comment]
Isn’t that a duplicate?
https://github.com/FirebirdSQL/NETProvider/issues/638

**Comment by cincuranet** [comment]
Nope. The #638 is about EF6, this is EF Core.
