### ISSUE TITLE
Scaffold-DbContext: blob sub type 1 mapping not found

### ISSUE THREAD

**Issue by DBernaert2** [FirebirdSQL/NETProvider#978]
Hi,

I try to scaffold my existing databavse (FB 3).
All entities are generated but columns of type 'bob sub type 1' are skipped.
With the message mapping not found.

Next to that I wanted to ask if there is a possibility to scaffold other settings like required, length, key, ...

Thx,
Dominique

**Comment by DBernaert2** [comment]
Never mind the question about scaffolding other questions, found that answer.

**Comment by cincuranet** [comment]
> I try to scaffold my existing databavse (FB 3).
All entities are generated but columns of type 'bob sub type 1' are skipped.
With the message mapping not found.

Provide a reproducible scenario.

> Next to that I wanted to ask if there is a possibility to scaffold other settings like required, length, key, ...

This is a place to report issues. If you want to have discussion, ask in the mailing list.

**Comment by DBernaert2** [comment]
Hi,

Database FB 3 containing fields with type of blob sub type 1, full specification of the column:
BLOB SUB_TYPE 1 SEGMENT SIZE 4096 CHARACTER SET UTF8
COLLATE UTF8

Scaffod database using this line:
scaffold-dbcontext "Data Source=127.0.0.1;Database=C:\\Databases\\Wave\\WAVE.FDB;User ID=SYSDBA;Password=Zandstraat11;Character Set=UTF8;Use Unicode=True;Login Prompt=False;Pooling=True;Max Pool Size=300;" FirebirdSql.EntityFrameworkCore.Firebird

All entities are generated but the type of fields mentionned above are skipped.
For each field of this type i get a line in the console:
Could not find type mapping for column 'ARTICLE_ARTICLES.EXTERNAL_DESCR_DUTCH_RTF' with data type 'BLOB SUB_TYPE 1'. Skipping column.
<img width="1055" alt="Screenshot" src="https://user-images.githubusercontent.com/88383248/128141151-3e6a9ab8-2e2f-44fb-b8d6-fe09cf4eec0e.png">

**Comment by cincuranet** [comment]
I tested it now with version 9.0.2 and scaffolding ran fine.
