### ISSUE TITLE
Different behavoir between V8.0.1 and V8.5.1 with WireCrypt- Setting

### ISSUE THREAD

**Issue by hhfiddelke** [FirebirdSQL/NETProvider#981]
When using WireCrypt = Enabled in connectionstring on client side:

`"user id=XXXX;password=XXXX;initial catalog=localhost:/XXXX.gdb;server type=Default;character set=UTF8;port number=3050;dialect=3;packet size=2048;cache pages=10;data source=localhost;wire crypt=Enabled;client library=/usr/share/cdk_pos/\fbclient.dll"`

and not configured "WireCrypt" on server side (OpenSuse 15.2, firebird 3.0.7.33374-lp152.2.3.1) in /etc/firebird/firebird.conf, but same if running both on Windows.

i get the exception:
`IscException: Client attempted to attach unencrypted but wire encryption is required.`

at this Stack position:
```
    FirebirdSql.Data.Client.Managed.GdsConnection.HandleResponseException(FirebirdSql.Data.Client.Managed.IResponse)
    FirebirdSql.Data.Client.Managed.Version10.GdsDatabase.ReadResponse()
    FirebirdSql.Data.Client.Managed.Version13.GdsDatabase.Attach(FirebirdSql.Data.Common.DatabaseParameterBufferBase, string, byte[])
    FirebirdSql.Data.FirebirdClient.FbConnectionInternal.Connect()
```
This was no problem with V8.0.1

**Comment by cincuranet** [comment]
Great catch. Please test [this](https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/suites/3541442291/artifacts/84784910) build (even scenarios outside this issue, if you feel so). Should be fixed.

**Comment by hhfiddelke** [comment]
On a first view 8.5.1.0 works like  8.0.1 on first start. 
I am currently investigating an issue in my software which needs testing FB- connection only until a first connection. So i am currently not able to test for other new "features" in the NETProvider.😢

**Comment by cincuranet** [comment]
OK. On my side it behaves correctly as well. 8.5.1.0 release tomorrow.
