### ISSUE TITLE
Executing procedures that insert data do not work...

### ISSUE THREAD

**Issue by adrianlmm** [FirebirdSQL/NETProvider#995]
When executing procedures that insert data in another table it returns the result, but the insertion doesn't work.

Example: In the attached project there is a database test.fdb and a test.sln project, the database  has two tables, DATA1 and DATA2, only  one has data, there is also a stored procedure PASS_DATA, what it does is insert the data from the table that has the data to the empty one, then deletes the data from de table where it got the data.
At the end returns a message that says "DATA1 PASSED TO DATA 2" or "DATA2 PASSED TO DATA1" depends of the case.

Execute the procedure via ISQL with "SELECT * FROM PASS_DATA", it will move the data from one table to the other and return the message.

Now, open the solution test.sln (just fix the path of the db in the connection string), it does the same and prints the result, but the data remains in the original table, it doesn't insert the data from one table to the other.

using FirebirdSql.Data.FirebirdClient" Version="8.5.3"

[test.zip](https://github.com/FirebirdSQL/NETProvider/files/7148249/test.zip)

**Comment by cincuranet** [comment]
You're missing `using`s (or explicit `Dispose` or explicit transaction handling).

```csharp
static void Main(string[] args)
{
    using (var con = new FbConnection(@"User=SYSDBA;Password=masterkey;Database=C:\Users\Jiri\Downloads\test\TEST.FDB;DataSource=127.0.0.1; Port=3050;Dialect=3; Charset=UTF8;Role=;Connection lifetime=15;Pooling=true; MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;"))
    {
        con.Open();
        using (var com = new FbCommand("SELECT * FROM PASS_DATA", con))
        {
            using (var reader = com.ExecuteReader())
            {
                if (reader.Read())
                {
                    Console.WriteLine(reader.GetString(0));
                }
            }
        }
        con.Close();
    }
            
    Console.WriteLine("End of process");
    Console.ReadLine();
}
```
