### ISSUE TITLE
object TABLE "xxx" is in use

### ISSUE THREAD

**Issue by fishcodelib** [FirebirdSQL/NETProvider#996]
Firebird: 4.0.0.2496-1-x64
FirebirdSql.Data.FirebirdClient: 8.5.3.0
OS: Windows 10
var ConnectionString = @"DataSource=localhost;ServerType=Embedded;Database=""test.fdb"";User ID=SYSDBA;Password=masterkey;Pooling=False;client library=C:\Firebird-4.0.0.2496-1-x64\fbclient.dll";
FbConnection.CreateDatabase(ConnectionString,4096,true,true);
using (var conn = new FbConnection(ConnectionString))
{
	conn.Open();
	Console.WriteLine(conn.ServerVersion);
	using (var cmd = conn.CreateCommand())
	{
		cmd.CommandText = @"CREATE TABLE ""test"" (""ctimestamptz"" timestamp with time zone, ""ctimetz"" time with time zone)";
		cmd.ExecuteNonQuery();
		cmd.CommandText = @"select * from ""test""";
		using (var reader = cmd.ExecuteReader())
		{ //Known issues: https://github.com/FirebirdSQL/NETProvider/issues/905
			//while (reader.Read()) //Exception thrown: 'Unknown time zone ID.' 
			//{
			//	Console.WriteLine(reader[0]);
			//}
		}
	}
	using (var cmd = conn.CreateCommand())
	{
		cmd.CommandText = @"DROP TABLE ""test""";
		cmd.ExecuteNonQuery(); //Exception thrown: unsuccessful metadata update object TABLE "test" is in use'
	}
}

**Comment by cincuranet** [comment]
Unknown timezone error because of #998.
