### ISSUE TITLE
Q: Using events with v8.x

### ISSUE THREAD

**Issue by cahoerner** [FirebirdSQL/NETProvider#999]
I'm about to upgrade our applications from FirebirdClient 6.4.0.0 to a more recent release.
What I found is that there is trouble with the database events.
Our existing code for registering events was working fine with 6.4.0.0 and still working with 7.10.1.0. (not significantly different from the sample code which is still around.)
I already found out that starting with 8.0.0.0 we need an additional call to FbRemoteEvent.Open() before queueing the event names, but that doesn't seem to be sufficient. After posting an event and committing, the handler doesn't get invoked.
I've also tried asynchronous calls, but only ran into additional issues with assembly dependencies. Anyway, I'd prefer to stay synchronous.
Any hints what might be missing? Or might there be a bug in FbRemoteEvent?
Thanks in advance.

**Comment by cincuranet** [comment]
The `Open` is [documented](https://github.com/FirebirdSQL/NETProvider/issues/913) as [breaking change](https://github.com/FirebirdSQL/NETProvider/issues?q=label%3A%22fix-version%3A+8.0.0.0%22+label%3Abreaking) for 8.x.

Your code is just a snippet not a something I can try to run. You can check the [tests](https://github.com/FirebirdSQL/NETProvider/blob/master/Provider/src/FirebirdSql.Data.FirebirdClient.Tests/FbRemoteEventTests.cs#L34) for this and compare it to what you're doing. Or create new issue with reproducible test case.
